package online.kingdomkeys.kingdomkeys.lib;

import static online.kingdomkeys.kingdomkeys.item.ModItems.*;

import java.util.ArrayList;
import java.util.List;

import net.minecraft.item.Item;

public class Lists {

    public static List<String> recipes = new ArrayList<String>();

    public static List<Item> Xemnas = new ArrayList<Item>();
    public static List<Item> Xigbar = new ArrayList<Item>();
    public static List<Item> Xaldin = new ArrayList<Item>();
    public static List<Item> Vexen = new ArrayList<Item>();
    public static List<Item> Lexaeus = new ArrayList<Item>();
    public static List<Item> Zexion = new ArrayList<Item>();
    public static List<Item> Saix = new ArrayList<Item>();
    public static List<Item> Axel = new ArrayList<Item>();
    public static List<Item> Demyx = new ArrayList<Item>();
    public static List<Item> Luxord = new ArrayList<Item>();
    public static List<Item> Marluxia = new ArrayList<Item>();
    public static List<Item> Larxene = new ArrayList<Item>();
    public static List<Item> Roxas = new ArrayList<>();

    public static List<Item> getListForMember(Utils.OrgMember member) {
        switch (member) {
            case AXEL: return Axel;
            case DEMYX: return Demyx;
            case LARXENE: return Larxene;
            case LEXAEUS: return Lexaeus;
            case LUXORD: return Luxord;
            case MARLUXIA: return Marluxia;
            case ROXAS: return Roxas;
            case SAIX: return Saix;
            case VEXEN: return Vexen;
            case XALDIN: return Xaldin;
            case XEMNAS: return Xemnas;
            case XIGBAR: return Xigbar;
            case ZEXION: return Zexion;
            case NONE: return null;
        }
        return null;
    }

    public static void init () {

        //Xemnas
        Xemnas.add(malice);
        Xemnas.add(sanction);
        Xemnas.add(overlord);
        Xemnas.add(veneration);
        Xemnas.add(autocracy);
        Xemnas.add(conquest);
        Xemnas.add(terminus);
        Xemnas.add(judgement);
        Xemnas.add(discipline);
        Xemnas.add(aristocracy);
        Xemnas.add(superiority);
        Xemnas.add(aggression);
        Xemnas.add(fury);
        Xemnas.add(despair);
        Xemnas.add(triumph);
        Xemnas.add(ruination);
        Xemnas.add(domination);
        Xemnas.add(annihilation);
        Xemnas.add(tyrant);
        Xemnas.add(magnificence);
        Xemnas.add(infinity);
        Xemnas.add(interdiction);
        Xemnas.add(roundFan);
        Xemnas.add(absolute);

        //Xigbar
        Xigbar.add(standalone);
        Xigbar.add(killerbee);
        Xigbar.add(stingray);
        Xigbar.add(counterweight);
        Xigbar.add(precision);
        Xigbar.add(dualHead);
        Xigbar.add(bahamut);
        Xigbar.add(gullwing);
        Xigbar.add(blueFrame);
        Xigbar.add(starShell);
        Xigbar.add(sunrise);
        Xigbar.add(ignition);
        Xigbar.add(armstrong);
        Xigbar.add(hardBoiledHeat);
        Xigbar.add(diabloEye);
        Xigbar.add(doubleTap);
        Xigbar.add(stardust);
        Xigbar.add(energyMuzzle);
        Xigbar.add(crimeAndPunishment);
        Xigbar.add(cupidsArrow);
        Xigbar.add(finalWeapon);
        Xigbar.add(sharpshooter);
        Xigbar.add(dryer);
        Xigbar.add(trumpet);

        //Xaldin
        Xaldin.add(zephyr);
        Xaldin.add(moonglade);
        Xaldin.add(aer);
        Xaldin.add(nescience);
        Xaldin.add(brume);
        Xaldin.add(asura);
        Xaldin.add(crux);
        Xaldin.add(paladin);
        Xaldin.add(fellking);
        Xaldin.add(nightcloud);
        Xaldin.add(shimmer);
        Xaldin.add(vortex);
        Xaldin.add(scission);
        Xaldin.add(heavenfall);
        Xaldin.add(aether);
        Xaldin.add(mazzaroth);
        Xaldin.add(hegemon);
        Xaldin.add(foxfire);
        Xaldin.add(yaksha);
        Xaldin.add(cynosura);
        Xaldin.add(dragonreign);
        Xaldin.add(lindworm);
        Xaldin.add(broom);
        Xaldin.add(wyvern);

        //Vexen
        Vexen.add(testerZero);
        Vexen.add(productOne);
        Vexen.add(deepFreeze);
        Vexen.add(cryoliteShield);
        Vexen.add(falseTheory);
        Vexen.add(glacier);
        Vexen.add(absoluteZero);
        Vexen.add(gunz);
        Vexen.add(mindel);
        Vexen.add(snowslide);
        Vexen.add(iceberg);
        Vexen.add(inquisition);
        Vexen.add(scrutiny);
        Vexen.add(empiricism);
        Vexen.add(edification);
        Vexen.add(contrivance);
        Vexen.add(wurm);
        Vexen.add(subzero);
        Vexen.add(coldBlood);
        Vexen.add(diamondShield);
        Vexen.add(aegis);
        Vexen.add(frozenPride);
        Vexen.add(potLid);
        Vexen.add(snowman);

        //Lexaeus
        Lexaeus.add(reticence);
        Lexaeus.add(goliath);
        Lexaeus.add(copperRed);
        Lexaeus.add(daybreak);
        Lexaeus.add(colossus);
        Lexaeus.add(ursaMajor);
        Lexaeus.add(megacosm);
        Lexaeus.add(terrene);
        Lexaeus.add(fuligin);
        Lexaeus.add(hardWinter);
        Lexaeus.add(firefly);
        Lexaeus.add(harbinger);
        Lexaeus.add(redwood);
        Lexaeus.add(sequoia);
        Lexaeus.add(ironBlack);
        Lexaeus.add(earthshine);
        Lexaeus.add(octiron);
        Lexaeus.add(hyperion);
        Lexaeus.add(clarity);
        Lexaeus.add(oneThousandAndOneNights);
        Lexaeus.add(cardinalVirtue);
        Lexaeus.add(skysplitter);
        Lexaeus.add(bleepBloopBop);
        Lexaeus.add(monolith);

        //Zexion
        Zexion.add(blackPrimer);
        Zexion.add(whiteTome);
        Zexion.add(illicitResearch);
        Zexion.add(buriedSecrets);
        Zexion.add(arcaneCompendium);
        Zexion.add(dissentersNotes);
        Zexion.add(nefariousCodex);
        Zexion.add(mysticAlbum);
        Zexion.add(cursedManual);
        Zexion.add(tabooText);
        Zexion.add(eldritchEsoterica);
        Zexion.add(freakishBestiary);
        Zexion.add(madmansVita);
        Zexion.add(untitledWritings);
        Zexion.add(abandonedDogma);
        Zexion.add(atlasOfOmens);
        Zexion.add(revoltingScrapbook);
        Zexion.add(lostHeterodoxy);
        Zexion.add(otherworldlyTales);
        Zexion.add(indescribableLore);
        Zexion.add(radicalTreatise);
        Zexion.add(bookOfRetribution);
        Zexion.add(midnightSnack);
        Zexion.add(dearDiary);

        //Saix
        Saix.add(newMoon);
        Saix.add(werewolf);
        Saix.add(artemis);
        Saix.add(luminary);
        Saix.add(selene);
        Saix.add(moonrise);
        Saix.add(astrologia);
        Saix.add(crater);
        Saix.add(lunarPhase);
        Saix.add(crescent);
        Saix.add(gibbous);
        Saix.add(berserker);
        Saix.add(twilight);
        Saix.add(queenOfTheNight);
        Saix.add(balsamicMoon);
        Saix.add(orbit);
        Saix.add(lightYear);
        Saix.add(kingOfTheNight);
        Saix.add(moonset);
        Saix.add(horoscope);
        Saix.add(dichotomy);
        Saix.add(lunatic);
        Saix.add(justDesserts);
        Saix.add(bunnymoon);

        //Axel
        Axel.add(ashes);
        Axel.add(doldrums);
        Axel.add(delayedAction);
        Axel.add(diveBombers);
        Axel.add(combustion);
        Axel.add(moulinRouge);
        Axel.add(blazeOfGlory);
        Axel.add(prometheus);
        Axel.add(ifrit);
        Axel.add(magmaOcean);
        Axel.add(volcanics);
        Axel.add(inferno);
        Axel.add(sizzlingEdge);
        Axel.add(corona);
        Axel.add(ferrisWheel);
        Axel.add(burnout);
        Axel.add(omegaTrinity);
        Axel.add(outbreak);
        Axel.add(doubleEdge);
        Axel.add(wildfire);
        Axel.add(prominence);
        Axel.add(eternalFlames);
        Axel.add(pizzaCut);
        Axel.add(conformers);

        //Demyx
        Demyx.add(basicModel);
        Demyx.add(tuneUp);
        Demyx.add(quartet);
        Demyx.add(quintet);
        Demyx.add(overture);
        Demyx.add(oldHand);
        Demyx.add(daCapo);
        Demyx.add(powerChord);
        Demyx.add(fermata);
        Demyx.add(interlude);
        Demyx.add(serenade);
        Demyx.add(songbird);
        Demyx.add(riseToFame);
        Demyx.add(rockStar);
        Demyx.add(eightFinger);
        Demyx.add(concerto);
        Demyx.add(harmonics);
        Demyx.add(millionBucks);
        Demyx.add(fortissimo);
        Demyx.add(upToEleven);
        Demyx.add(sanctuary);
        Demyx.add(arpeggio);
        Demyx.add(princeOfAwesome);
        Demyx.add(afterSchool);

        //Luxord
        Luxord.add(theFool);
        Luxord.add(theMagician);
        Luxord.add(theStar);
        Luxord.add(theMoon);
        Luxord.add(justice);
        Luxord.add(theHierophant);
        Luxord.add(theWorld);
        Luxord.add(temperance);
        Luxord.add(theHighPriestess);
        Luxord.add(theTower);
        Luxord.add(theHangedMan);
        Luxord.add(death);
        Luxord.add(theHermit);
        Luxord.add(strength);
        Luxord.add(theLovers);
        Luxord.add(theChariot);
        Luxord.add(theSun);
        Luxord.add(theDevil);
        Luxord.add(theEmpress);
        Luxord.add(theEmperor);
        Luxord.add(theJoker);
        Luxord.add(fairGame);
        Luxord.add(finestFantasy13);
        Luxord.add(highRollersSecret);

        //Marluxia
        Marluxia.add(fickleErica);
        Marluxia.add(jiltedAnemone);
        Marluxia.add(proudAmaryllis);
        Marluxia.add(madSafflower);
        Marluxia.add(poorMelissa);
        Marluxia.add(tragicAllium);
        Marluxia.add(mournfulCineria);
        Marluxia.add(pseudoSilene);
        Marluxia.add(faithlessDigitalis);
        Marluxia.add(grimMuscari);
        Marluxia.add(docileVallota);
        Marluxia.add(quietBelladonna);
        Marluxia.add(partingIpheion);
        Marluxia.add(loftyGerbera);
        Marluxia.add(gallantAchillea);
        Marluxia.add(noblePeony);
        Marluxia.add(fearsomeAnise);
        Marluxia.add(vindictiveThistle);
        Marluxia.add(fairHelianthus);
        Marluxia.add(solemnMagnolia);
        Marluxia.add(hallowedLotus);
        Marluxia.add(gracefulDahlia);
        Marluxia.add(stirringLadle);
        Marluxia.add(daintyBellflowers);

        //Larxene
        Larxene.add(trancheuse);
        Larxene.add(orage);
        Larxene.add(tourbillon);
        Larxene.add(tempete);
        Larxene.add(carmin);
        Larxene.add(meteore);
        Larxene.add(etoile);
        Larxene.add(irregulier);
        Larxene.add(dissonance);
        Larxene.add(eruption);
        Larxene.add(soleilCouchant);
        Larxene.add(indigo);
        Larxene.add(vague);
        Larxene.add(deluge);
        Larxene.add(rafale);
        Larxene.add(typhon);
        Larxene.add(extirpeur);
        Larxene.add(croixDuSud);
        Larxene.add(lumineuse);
        Larxene.add(clairDeLune);
        Larxene.add(volDeNuit);
        Larxene.add(foudre);
        Larxene.add(demoiselle);
        Larxene.add(ampoule);

        Roxas.add(kingdomKey);
        Roxas.add(missingAche);
        Roxas.add(ominousBlight);
        Roxas.add(abaddonPlasma);
        Roxas.add(painOfSolitude);
        Roxas.add(signOfInnocence);
        Roxas.add(crownOfGuilt);
        Roxas.add(abyssalTide);
        Roxas.add(leviathan);
        Roxas.add(trueLightsFlight);
        Roxas.add(rejectionOfFate);
        Roxas.add(midnightRoar);
        Roxas.add(glimpseOfDarkness);
        Roxas.add(totalEclipse);
        Roxas.add(silentDirge);
        Roxas.add(lunarEclipse);
        Roxas.add(darkerThanDark);
        Roxas.add(astralBlast);
        Roxas.add(maverickFlare);
        Roxas.add(twilightBlaze);
        Roxas.add(omegaWeapon);
        Roxas.add(oathkeeper);
        Roxas.add(twoBecomeOne);
        Roxas.add(oblivion);
        Roxas.add(umbrella);
        Roxas.add(aubade);
        Roxas.add(woodenStick);

        //Keyblades
        recipes.add(abaddonPlasma.getTranslationKey());
        recipes.add(abyssalTide.getTranslationKey());
        recipes.add(allForOne.getTranslationKey());
        recipes.add(invisKeyblade.getTranslationKey());
        recipes.add(astralBlast.getTranslationKey());
        recipes.add(aubade.getTranslationKey());
        recipes.add(bondOfFlame.getTranslationKey());
        recipes.add(brightcrest.getTranslationKey());
        recipes.add(chaosRipper.getTranslationKey());
        recipes.add(circleOfLife.getTranslationKey());
        recipes.add(counterpoint.getTranslationKey());
        recipes.add(crabclaw.getTranslationKey());
        recipes.add(crownOfGuilt.getTranslationKey());
        recipes.add(darkerThanDark.getTranslationKey());
        recipes.add(darkgnaw.getTranslationKey());
        recipes.add(decisivePumpkin.getTranslationKey());
        recipes.add(destinysEmbrace.getTranslationKey());
        recipes.add(diamondDust.getTranslationKey());
        recipes.add(divewing.getTranslationKey());
        recipes.add(divineRose.getTranslationKey());
        recipes.add(dreamShield.getTranslationKey());
        recipes.add(dreamStaff.getTranslationKey());
        recipes.add(dreamSword.getTranslationKey());
        recipes.add(dualDisc.getTranslationKey());
        recipes.add(earthshaker.getTranslationKey());
        recipes.add(endOfPain.getTranslationKey());
        recipes.add(endsOfTheEarth.getTranslationKey());
        recipes.add(fairyHarp.getTranslationKey());
        recipes.add(fairyStars.getTranslationKey());
        recipes.add(fatalCrest.getTranslationKey());
        recipes.add(fenrir.getTranslationKey());
        recipes.add(ferrisGear.getTranslationKey());
        recipes.add(followtheWind.getTranslationKey());
        recipes.add(frolicFlame.getTranslationKey());
        recipes.add(glimpseOfDarkness.getTranslationKey());
        recipes.add(guardianBell.getTranslationKey());
        recipes.add(guardianSoul.getTranslationKey());
        recipes.add(gullWing.getTranslationKey());
        recipes.add(herosCrest.getTranslationKey());
        recipes.add(hiddenDragon.getTranslationKey());
        recipes.add(hyperdrive.getTranslationKey());
        recipes.add(incompleteKiblade.getTranslationKey());
        recipes.add(jungleKing.getTranslationKey());
        recipes.add(keybladeOfPeoplesHearts.getTranslationKey());
        recipes.add(kiblade.getTranslationKey());
        recipes.add(kingdomKey.getTranslationKey());
        recipes.add(kingdomKeyD.getTranslationKey());
        recipes.add(knockoutPunch.getTranslationKey());
        recipes.add(ladyLuck.getTranslationKey());
        recipes.add(flameLiberator.getTranslationKey());
        recipes.add(gulasKeyblade.getTranslationKey());
        recipes.add(leviathan.getTranslationKey());
        recipes.add(lionheart.getTranslationKey());
        recipes.add(lostMemory.getTranslationKey());
        recipes.add(lunarEclipse.getTranslationKey());
        recipes.add(markOfAHero.getTranslationKey());
        recipes.add(mastersDefender.getTranslationKey());
        recipes.add(maverickFlare.getTranslationKey());
        recipes.add(metalChocobo.getTranslationKey());
        recipes.add(midnightRoar.getTranslationKey());
        recipes.add(mirageSplit.getTranslationKey());
        recipes.add(missingAche.getTranslationKey());
        recipes.add(monochrome.getTranslationKey());
        recipes.add(moogleOGlory.getTranslationKey());
        recipes.add(mysteriousAbyss.getTranslationKey());
        recipes.add(nightmaresEnd.getTranslationKey());
        recipes.add(nightmaresEndAndMirageSplit.getTranslationKey());
        recipes.add(noName.getTranslationKey());
        recipes.add(noNameBBS.getTranslationKey());
        recipes.add(oathkeeper.getTranslationKey());
        recipes.add(oblivion.getTranslationKey());
        recipes.add(oceansRage.getTranslationKey());
        recipes.add(olympia.getTranslationKey());
        recipes.add(omegaWeapon.getTranslationKey());
        recipes.add(ominousBlight.getTranslationKey());
        recipes.add(oneWingedAngel.getTranslationKey());
        recipes.add(painOfSolitude.getTranslationKey());
        recipes.add(photonDebugger.getTranslationKey());
        recipes.add(pixiePetal.getTranslationKey());
        recipes.add(pumpkinhead.getTranslationKey());
        recipes.add(rainfell.getTranslationKey());
        recipes.add(rejectionOfFate.getTranslationKey());
        recipes.add(royalRadiance.getTranslationKey());
        recipes.add(rumblingRose.getTranslationKey());
        recipes.add(shootingStar.getTranslationKey());
        recipes.add(signOfInnocence.getTranslationKey());
        recipes.add(silentDirge.getTranslationKey());
        recipes.add(skullNoise.getTranslationKey());
        recipes.add(sleepingLion.getTranslationKey());
        recipes.add(soulEater.getTranslationKey());
        recipes.add(spellbinder.getTranslationKey());
        recipes.add(starlight.getTranslationKey());
        recipes.add(starSeeker.getTranslationKey());
        recipes.add(stormfall.getTranslationKey());
        recipes.add(strokeOfMidnight.getTranslationKey());
        recipes.add(sweetDreams.getTranslationKey());
        recipes.add(sweetMemories.getTranslationKey());
        recipes.add(sweetstack.getTranslationKey());
        recipes.add(threeWishes.getTranslationKey());
        recipes.add(totalEclipse.getTranslationKey());
        recipes.add(treasureTrove.getTranslationKey());
        recipes.add(trueLightsFlight.getTranslationKey());
        recipes.add(twilightBlaze.getTranslationKey());
        recipes.add(twoBecomeOne.getTranslationKey());
        recipes.add(ultimaWeaponBBS.getTranslationKey());
        recipes.add(ultimaWeaponDDD.getTranslationKey());
        recipes.add(ultimaWeaponKH1.getTranslationKey());
        recipes.add(ultimaWeaponKH2.getTranslationKey());
        recipes.add(ultimaWeaponKH3.getTranslationKey());
        recipes.add(umbrella.getTranslationKey());
        recipes.add(unbound.getTranslationKey());
        recipes.add(irasKeyblade.getTranslationKey());
        recipes.add(acedsKeyblade.getTranslationKey());
        recipes.add(victoryLine.getTranslationKey());
        recipes.add(voidGear.getTranslationKey());
        recipes.add(avasKeyblade.getTranslationKey());
        recipes.add(waytotheDawn.getTranslationKey());
        recipes.add(waywardWind.getTranslationKey());
        recipes.add(winnersProof.getTranslationKey());
        recipes.add(wishingLamp.getTranslationKey());
        recipes.add(wishingStar.getTranslationKey());
        recipes.add(woodenKeyblade.getTranslationKey());
        recipes.add(woodenStick.getTranslationKey());
        recipes.add(youngXehanortsKeyblade.getTranslationKey());
        recipes.add(zeroOne.getTranslationKey());
        
       /* TODO for(String keyblade : MainConfig.items.bannedKeyblades) {
        	if(recipes.indexOf("item."+keyblade) >= 0)
        		recipes.remove(recipes.indexOf("item."+keyblade));
        }*/
    }

}
