package online.kingdomkeys.kingdomkeys.lib;

public class Strings {
    // Records
    public static final String
		    Disc_Duration_Desc = "disc.duration.desc",
		    Disc_DurationUnits_Desc = "disc.durationunits.desc";
    
    //Dimensions
    public static final String
    		twilightTown = "twilight_town",
    		destinyIslands = "destiny_islands",
    		diveToTheHeart = "dive_to_the_heart",
    		stationOfSorrow = "station_of_sorrow",
			castleOblivionInterior = "castle_oblivion_interior",
			castleOblivion = "castle_oblivion",
			daybreakTown = "daybreak_town",
			oceanBetween = "ocean_between";

    // Magics
    public static final String
		Mag_Prefix = "magic_",

		Magic_Fire = Mag_Prefix + "fire",
		Magic_Fira = Mag_Prefix + "fira",
		Magic_Firaga = Mag_Prefix + "firaga",
		Magic_Firaza = Mag_Prefix + "firaza",

		Magic_Blizzard = Mag_Prefix + "blizzard",
		Magic_Blizzara = Mag_Prefix + "blizzara",
		Magic_Blizzaga = Mag_Prefix + "blizzaga",
		Magic_Blizzaza = Mag_Prefix + "blizzaza",

		Magic_Water = Mag_Prefix + "water",
		Magic_Watera = Mag_Prefix + "watera",
		Magic_Waterga = Mag_Prefix + "waterga",
		Magic_Waterza = Mag_Prefix + "waterza",

		Magic_Thunder = Mag_Prefix + "thunder",
		Magic_Thundara = Mag_Prefix + "thundara",
		Magic_Thundaga = Mag_Prefix + "thundaga",
		Magic_Thundaza = Mag_Prefix + "thundaza",

		Magic_Cure = Mag_Prefix + "cure",
		Magic_Cura = Mag_Prefix + "cura",
		Magic_Curaga = Mag_Prefix + "curaga",
		Magic_Curaza = Mag_Prefix + "curaza",

		Magic_AeroShield = Mag_Prefix + "aero_shield",
		Magic_AeroraShield = Mag_Prefix + "aerora_shield",
		Magic_AerogaShield = Mag_Prefix + "aeroga_shield",

		Magic_Aero = Mag_Prefix + "aero",
		Magic_Aerora = Mag_Prefix + "aerora",
		Magic_Aeroga = Mag_Prefix + "aeroga",

		Magic_Magnet = Mag_Prefix + "magnet",
		Magic_Magnera = Mag_Prefix + "magnera",
		Magic_Magnega = Mag_Prefix + "magnega",

		Magic_Reflect = Mag_Prefix + "reflect",
		Magic_Reflera = Mag_Prefix + "reflera",
		Magic_Reflega = Mag_Prefix + "reflega",

		Magic_Gravity = Mag_Prefix + "gravity",
		Magic_Gravira = Mag_Prefix + "gravira",
		Magic_Graviga = Mag_Prefix + "graviga",

		Magic_ZeroGravity = Mag_Prefix + "zerogravity",
		Magic_ZeroGravira = Mag_Prefix + "zerogravira",
		Magic_ZeroGraviga = Mag_Prefix + "zerograviga",

		Magic_Stop = Mag_Prefix + "stop",
		Magic_Stopra = Mag_Prefix + "stopra",
		Magic_Stopga = Mag_Prefix + "stopga",

		//BBS / DDD
		Magic_DarkFiraga = Mag_Prefix + "darkfiraga",
		Magic_TripleFiraga = Mag_Prefix + "triplefiraga",
		Magic_CrawlingFiraga = Mag_Prefix + "crawlingfiraga",
		Magic_FissionFiraga = Mag_Prefix + "fissionfiraga",
		Magic_FiragaBurst = Mag_Prefix + "firagaburst",
		Magic_Ignite = Mag_Prefix + "ignite",

		Magic_TripleBlizzard = Mag_Prefix + "tripleblizzaga",
		Magic_DeepFreeze = Mag_Prefix + "deepfreeze",
		Magic_Glacier = Mag_Prefix + "glacier",
		Magic_IceBarrage = Mag_Prefix + "icebarrage",

		Magic_ThundagaShot = Mag_Prefix + "thundagashot",
		Magic_TriplePlasma = Mag_Prefix + "tripleplasma",

		Magic_Blackout = Mag_Prefix + "blackout",
		Magic_Poison = Mag_Prefix + "posion",

		Magic_Balloon = Mag_Prefix + "balloon",
		Magic_Balloonra = Mag_Prefix + "balloonra",
		Magic_Balloonga = Mag_Prefix + "balloonga",

		Magic_Warp = Mag_Prefix + "warp",
		Magic_Faith = Mag_Prefix + "faith",
		Magic_MineShield = Mag_Prefix + "mine_shield",
		Magic_MineSquare = Mag_Prefix + "mine_square",
		Magic_SeekerMine = Mag_Prefix + "seeker_mine",

		Magic_Spark = Mag_Prefix + "spark",
		Magic_Sparkra = Mag_Prefix + "sparkra",
		Magic_Sparkga = Mag_Prefix + "sparkga",

		Magic_Bind = Mag_Prefix + "bind",
		Magic_Confuse = Mag_Prefix + "confuse",
		Magic_Esuna = Mag_Prefix + "esuna",
		Magic_Mini = Mag_Prefix + "mini",
		Magic_Slow = Mag_Prefix + "slow";


	// Drive Forms
    public static final String
    		DF_Prefix = "form_",
            Form_Valor = DF_Prefix+"valor",
            Form_Wisdom = DF_Prefix+"wisdom",
            Form_Limit = DF_Prefix+"limit",
            Form_Master = DF_Prefix+"master",
            Form_Final = DF_Prefix+"final",
            Form_Anti = DF_Prefix+"anti";
            
    // Limits
       public static final String
			LaserCircle = "laser_circle",
       		LaserDome = "laser_dome",
       		ArrowRain = "arrow_rain",
			SlowThunderTrail = "slow_thunder_trail",
			FastThunderTrail = "fast_thunder_trail",
		    FlameRing = "flame_ring",
			FlameWall = "flame_wall",
			LanceStorm = "lance_storm",
			BerserkClaymore = "berserk_claymore",
			FallingSpear = "falling_spear",
			IcePillars = "ice_pillars",
			Powerup = "powerup",
			RockyPillars = "rocky_pillars",
			WaterWall = "water_wall",
			WaterTrail = "water_trail",
			CardRing = "card_ring",
			ScytheDash = "scythe_dash",
			PetalVoid = "petal_void",
			LightBarrage = "light_barrage",
			IllusoryMeteor = "illusory_meteor";
       
    // Shotlocks
       public static final String
       		DarkVolley = "dark_volley",
       		Ragnarok = "ragnarok",
       		SonicShadow = "sonic_shadow",
       		PrismRain = "prism_rain",
			UltimaCannon = "ultima_cannon",
			FlameSalvo = "flame_salvo",
			AbsoluteZero = "absolute_zero",
			Thunderstorm = "thunderstorm",
			ChaosSnake = "chaos_snake",
			BubbleBlaster = "bubble_blaster",
			BioBarrage = "bio_barrage",
			PulseBomb = "pulse_bomb",
			PhotonCharge = "photon_charge",
			LightningRay = "lightning_ray",
			MeteorShower = "meteor_shower",
			Multivortex = "multivortex",
			Lightbloom = "lightbloom";

	// Shotlock items
	public static final String
			ShotlockItemDarkVolley = "shotlock_dark_volley",
			ShotlockItemRagnarok = "shotlock_ragnarok",
			ShotlockItemSonicShadow = "shotlock_sonic_shadow",
			ShotlockItemPrismRain = "shotlock_prism_rain",
			ShotlockItemUltimaCannon = "shotlock_ultima_cannon",
			ShotlockItemFlameSalvo = "shotlock_flame_salvo",
			ShotlockItemAbsoluteZero = "shotlock_absolute_zero",
			ShotlockItemThunderstorm = "shotlock_thunderstorm",
			ShotlockItemChaosSnake = "shotlock_chaos_snake",
			ShotlockItemBubbleBlaster = "shotlock_bubble_blaster",
			ShotlockItemBioBarrage = "shotlock_bio_barrage",
			ShotlockItemPulseBomb = "shotlock_pulse_bomb",
			ShotlockItemPhotonCharge = "shotlock_photon_charge",
			ShotlockItemLightningRay = "shotlock_lightning_ray",
			ShotlockItemMeteorShower = "shotlock_meteor_shower",
			ShotlockItemMultivortex = "shotlock_multivortex",
			ShotlockItemLightbloom = "shotlock_lightbloom";
    
    // Reaction Commands
       public static final String
       		autoValorRC = "rc_auto_valor",
       		autoWisdomRC = "rc_auto_wisdom",
       		autoLimitRC = "rc_auto_limit",
       		autoMasterRC = "rc_auto_master",
       		autoFinalRC = "rc_auto_final",
       		launchRC = "rc_launch",
       		landRC = "rc_land",
       		reversalRC = "rc_reversal";

    // Abilities
    public static final String
    		AB_Prefix = "ability_",
    		//Action
    		autoValor = AB_Prefix +"auto_valor",
    		autoWisdom = AB_Prefix +"auto_wisdom",
    		autoLimit = AB_Prefix +"auto_limit",
    		autoMaster = AB_Prefix +"auto_master",
    		autoFinal = AB_Prefix +"auto_final",
    		strikeRaid = AB_Prefix +"strike_raid",
			flowStep = AB_Prefix +"flowstep",
    		
    		//Growth
    		highJump = AB_Prefix +"high_jump",
    		quickRun = AB_Prefix +"quick_run",
    		dodgeRoll = AB_Prefix +"dodge_roll",
    		aerialDodge = AB_Prefix +"aerial_dodge",
    		glide = AB_Prefix +"glide",

			airSlide = AB_Prefix +"air_slide",
			wallKick = AB_Prefix +"wall_kick",
			superJump = AB_Prefix +"superjump",
			superSlide = AB_Prefix +"superslide",

    		//Support
    		zeroExp = AB_Prefix +"zero_exp",
    		scan = AB_Prefix +"scan",
    		magicLockOn = AB_Prefix +"magic_lock_on",
    		leafBracer = AB_Prefix +"leaf_bracer",
    		hpGain = AB_Prefix +"hp_gain",
    		mpSafety = AB_Prefix +"mp_safety",
    		mpHaste = AB_Prefix +"mp_haste",
    		mpHastera = AB_Prefix +"mp_hastera",
    		mpHastega = AB_Prefix +"mp_hastega",
    		mpRage = AB_Prefix +"mp_rage",
    		endlessMagic = AB_Prefix +"endless_magic",
    		damageDrive = AB_Prefix +"damage_drive",
    		driveBoost = AB_Prefix +"drive_boost",
    		formBoost = AB_Prefix +"form_boost",
    		fullMPBlast = AB_Prefix +"full_mp_blast",
    		fireBoost =  AB_Prefix +"fire_boost",
			blizzardBoost =  AB_Prefix +"blizzard_boost",
			waterBoost =  AB_Prefix +"water_boost",
    		thunderBoost =  AB_Prefix +"thunder_boost",
    		experienceBoost =  AB_Prefix +"experience_boost",
    		treasureMagnet =  AB_Prefix +"treasure_magnet",
    		secondChance =  AB_Prefix +"second_chance",
    		onceMore = AB_Prefix +"once_more",
    		aerialRecovery = AB_Prefix +"aerial_recovery",
    		guard = AB_Prefix +"guard",
    		counterguard = AB_Prefix +"counterguard",
    		wizardsRuse =  AB_Prefix +"wizards_ruse",
    		extraCast =  AB_Prefix +"extra_cast",
    		damageControl =  AB_Prefix +"damage_control",
    		lightAndDarkness =  AB_Prefix +"light_and_darkness",
    		synchBlade = AB_Prefix +"synch_blade",
    		driveConverter = AB_Prefix +"drive_converter",
    		focusConverter = AB_Prefix +"focus_converter",
    		mpThrift = AB_Prefix +"mp_thrift",
    		criticalBoost = AB_Prefix +"critical_boost",
    		itemBoost = AB_Prefix +"item_boost",
    		jackpot = AB_Prefix +"jackpot",
    		luckyStrike = AB_Prefix +"lucky_lucky",
    		grandMagicHaste = AB_Prefix +"grand_magic_haste",
			grandMagicExtender = AB_Prefix +"grand_magic_extender",
			comboPlus = AB_Prefix +"combo_plus",
			negativeCombo = AB_Prefix +"negative_combo",
			finishingPlus = AB_Prefix +"finishing_plus",
			berserkCharge = AB_Prefix +"berserk_charge",
    		darkDomination = AB_Prefix +"dark_domination",
			protect = AB_Prefix + "protect",
			protectra = AB_Prefix + "protectra",
			protectga = AB_Prefix + "protectga",
            encounterPlus =  AB_Prefix +"encounter_plus",

    		firaza = AB_Prefix +"firaza",
    		blizzaza = AB_Prefix +"blizzaza",
    		waterza = AB_Prefix +"waterza",
    		thundaza = AB_Prefix +"thundaza",
   			curaza = AB_Prefix +"curaza";

    
    // Synthesis Materials
    public static final String
            SM_Rank = "sm.rank",
            SM_Rank_C = SM_Rank + ".c",
            SM_Rank_B = SM_Rank + ".b",
            SM_Rank_A = SM_Rank + ".a",
            SM_Rank_S = SM_Rank + ".s",

            SM_Shard = "_shard",
            SM_Stone = "_stone",
            SM_Gem = "_gem",
            SM_Crystal = "_crystal",

            SM_Blazing = "blazing",

            SM_BlazingShard = SM_Blazing + SM_Shard,
            SM_BlazingStone = SM_Blazing + SM_Stone,
            SM_BlazingGem = SM_Blazing + SM_Gem,
            SM_BlazingCrystal = SM_Blazing + SM_Crystal,

            SM_Soothing = "soothing",

            SM_SoothingShard = SM_Soothing + SM_Shard,
            SM_SoothingStone = SM_Soothing + SM_Stone,
            SM_SoothingGem = SM_Soothing + SM_Gem,
            SM_SoothingCrystal = SM_Soothing + SM_Crystal,

            SM_Writhing = "writhing",

            SM_WrithingShard = SM_Writhing + SM_Shard,
            SM_WrithingStone = SM_Writhing + SM_Stone,
            SM_WrithingGem = SM_Writhing + SM_Gem,
            SM_WrithingCrystal = SM_Writhing + SM_Crystal,

            SM_Betwixt = "betwixt",

            SM_BetwixtShard = SM_Betwixt + SM_Shard,
            SM_BetwixtStone = SM_Betwixt + SM_Stone,
            SM_BetwixtGem = SM_Betwixt + SM_Gem,
            SM_BetwixtCrystal = SM_Betwixt + SM_Crystal,

            SM_Wellspring = "wellspring",

            SM_WellspringShard = SM_Wellspring + SM_Shard,
            SM_WellspringStone = SM_Wellspring + SM_Stone,
            SM_WellspringGem = SM_Wellspring + SM_Gem,
            SM_WellspringCrystal = SM_Wellspring + SM_Crystal,

            SM_Frost = "frost",

            SM_FrostShard = SM_Frost + SM_Shard,
            SM_FrostStone = SM_Frost + SM_Stone,
            SM_FrostGem = SM_Frost + SM_Gem,
            SM_FrostCrystal = SM_Frost + SM_Crystal,

            SM_Lightning = "lightning",

            SM_LightningShard = SM_Lightning + SM_Shard,
            SM_LightningStone = SM_Lightning + SM_Stone,
            SM_LightningGem = SM_Lightning + SM_Gem,
            SM_LightningCrystal = SM_Lightning + SM_Crystal,

            SM_Lucid = "lucid",

            SM_LucidShard = SM_Lucid + SM_Shard,
            SM_LucidStone = SM_Lucid + SM_Stone,
            SM_LucidGem = SM_Lucid + SM_Gem,
            SM_LucidCrystal = SM_Lucid + SM_Crystal,

            SM_Pulsing = "pulsing",

            SM_PulsingShard = SM_Pulsing + SM_Shard,
            SM_PulsingStone = SM_Pulsing + SM_Stone,
            SM_PulsingGem = SM_Pulsing + SM_Gem,
            SM_PulsingCrystal = SM_Pulsing + SM_Crystal,

            SM_Mythril = "mythril",

            SM_MythrilShard = SM_Mythril + SM_Shard,
            SM_MythrilStone = SM_Mythril + SM_Stone,
            SM_MythrilGem = SM_Mythril + SM_Gem,
            SM_MythrilCrystal = SM_Mythril + SM_Crystal,

            SM_Remembrance = "remembrance",

            SM_RemembranceShard = SM_Remembrance + SM_Shard,
            SM_RemembranceStone = SM_Remembrance + SM_Stone,
            SM_RemembranceGem = SM_Remembrance + SM_Gem,
            SM_RemembranceCrystal = SM_Remembrance + SM_Crystal,

            SM_Hungry = "hungry",

            SM_HungryShard = SM_Hungry + SM_Shard,
            SM_HungryStone = SM_Hungry + SM_Stone,
            SM_HungryGem = SM_Hungry + SM_Gem,
            SM_HungryCrystal = SM_Hungry + SM_Crystal,

            SM_Tranquility = "tranquility",

            SM_TranquilityShard = SM_Tranquility + SM_Shard,
            SM_TranquilityStone = SM_Tranquility + SM_Stone,
            SM_TranquilityGem = SM_Tranquility + SM_Gem,
            SM_TranquilityCrystal = SM_Tranquility + SM_Crystal,

            SM_Twilight = "twilight",

            SM_TwilightShard = SM_Twilight + SM_Shard,
            SM_TwilightStone = SM_Twilight + SM_Stone,
            SM_TwilightGem = SM_Twilight + SM_Gem,
            SM_TwilightCrystal = SM_Twilight + SM_Crystal,

            SM_Stormy = "stormy",

            SM_StormyShard = SM_Stormy + SM_Shard,
            SM_StormyStone = SM_Stormy + SM_Stone,
            SM_StormyGem = SM_Stormy + SM_Gem,
            SM_StormyCrystal = SM_Stormy + SM_Crystal,

            SM_Sinister = "sinister",

            SM_SinisterShard = SM_Sinister + SM_Shard,
            SM_SinisterStone = SM_Sinister + SM_Stone,
            SM_SinisterGem = SM_Sinister + SM_Gem,
            SM_SinisterCrystal = SM_Sinister + SM_Crystal,

            SM_Orichalcum = "orichalcum",
            SM_OrichalcumPlus = "orichalcumplus",
            SM_ManifestIllusion = "manifest_illusion",
            SM_LostIllusion = "lost_illusion",

            SM_Fluorite = "fluorite",
            SM_Damascus = "damascus",
            SM_Adamantite = "adamantite",
            SM_Electrum = "electrum",

            SM_EvanescentCrystal = "evanescent" + SM_Crystal,
            SM_IllusoryCrystal = "illusory" + SM_Crystal;
    
    //Armors
    public static final String
    		helmet = "helmet",
    		chestplate = "chestplate",
    		leggings = "leggings",
    		boots = "boots",
    		
    		organization = "organization",
    		xemnas = "xemnas",
            antiCoat = "anticoat",
            terra = "terra",
            aqua = "aqua",
            ventus = "ventus",
            nightmareVentus = "nightmareventus",
            eraqus = "eraqus",
            xehanort = "xehanort",
            ux = "ux",
            vanitas = "vanitas",
            vanitasRemnant = "vanitas_remnant",
            darkRiku = "dark_riku",
            aced = "aced",
            ava = "ava",
            gula = "gula",
            invi = "invi",
            ira = "ira";

    //Level up messages
    public static final String
		    Stats_LevelUp_Str = "stats.levelUpStr",
		    Stats_LevelUp_Def = "stats.levelUpDef",
		    Stats_LevelUp_Magic = "stats.levelUpMag",
		    Stats_LevelUp_HP = "stats.levelUpHP",
		    Stats_LevelUp_MP = "stats.levelUpMP",
		    Stats_LevelUp_AP = "stats.levelUpAP",
		    Stats_LevelUp_FormGauge = "stats.levelUpFG",
			Stats_LevelUp_MaxAccessories = "stats.levelUpMaxAccessories",
			Stats_LevelUp_MaxArmors = "stats.levelUpMaxArmors",
		    Stats_LevelUp_MaxMagics = "stats.levelUpMaxMagics",
		    Stats_LevelUp_MaxItems = "stats.levelUpMaxItems",
			Stats_LevelNext = "stats.levelNext",
			Stats_MunnyGet = "stats.munnyGet";

    // Gui
    public static final String
            // Command Menu
            Gui_CommandMenu = "gui.commandmenu",
            Gui_CommandMenu_Command = Gui_CommandMenu + ".command",
            Gui_CommandMenu_Attack = Gui_CommandMenu + ".attack",
            Gui_CommandMenu_Portal = Gui_CommandMenu + ".portal",
            Gui_CommandMenu_Magic = Gui_CommandMenu + ".magic",
            Gui_CommandMenu_Items = Gui_CommandMenu + ".items",
            Gui_CommandMenu_Drive = Gui_CommandMenu + ".drive",
            Gui_CommandMenu_Limit = Gui_CommandMenu + ".limit",
            Gui_CommandMenu_Drive_Revert = Gui_CommandMenu + ".revert",
			Gui_CommandMenu_Target = Gui_CommandMenu + ".target",
          
            // Submenus
			Gui_CommandMenu_Items_Title = Gui_CommandMenu_Items + ".title",
            Gui_CommandMenu_Magic_Title = Gui_CommandMenu_Magic + ".title",
            Gui_CommandMenu_Portals_Title = Gui_CommandMenu_Portal + ".title",
            Gui_CommandMenu_Drive_Title = Gui_CommandMenu_Drive + ".title",
            Gui_CommandMenu_Limit_Title = Gui_CommandMenu_Limit + ".title",

            // Menu
            Gui_Menu = "gui.menu",
            Gui_Menu_Main = Gui_Menu + ".main",
            Gui_Menu_Main_Title = Gui_Menu_Main + ".title",
            Gui_Menu_Accept = Gui_Menu + ".accept",
			Gui_Menu_Cancel = Gui_Menu + ".cancel",
            Gui_Menu_Back = Gui_Menu + ".back",

            Gui_Menu_Main_Button = Gui_Menu_Main + ".button",
            Gui_Menu_Main_Button_Items = Gui_Menu_Main_Button + ".items",
            Gui_Menu_Main_Button_Abilities = Gui_Menu_Main_Button + ".abilities",
            Gui_Menu_Main_Button_Customize = Gui_Menu_Main_Button + ".customize",
            Gui_Menu_Main_Button_Party = Gui_Menu_Main_Button + ".party",
            Gui_Menu_Main_Button_Status = Gui_Menu_Main_Button + ".status",
            Gui_Menu_Main_Button_Journal = Gui_Menu_Main_Button + ".journal",
            Gui_Menu_Main_Button_Config = Gui_Menu_Main_Button + ".config",
			Gui_Menu_Main_Button_Style = Gui_Menu_Main_Button + ".style",
            Gui_Menu_Main_Synthesis_Tier = Gui_Menu_Main + ".synthesis_tier",
            Gui_Menu_Main_Munny = Gui_Menu_Main + ".munny",
            Gui_Menu_Main_Hearts = Gui_Menu_Main + ".hearts",
            Gui_Menu_Main_Time = Gui_Menu_Main + ".time",
            Gui_Menu_Main_Time_Spent = Gui_Menu_Main_Time + ".spent",
            
            Gui_Menu_Items = Gui_Menu + ".items",
            Gui_Menu_Items_Equipment = Gui_Menu_Items + ".equipment",
            Gui_Menu_Items_Stock = Gui_Menu_Items + ".stock",
            Gui_Menu_Items_Stock_Take = Gui_Menu_Items + ".stock.take",

            
            Gui_Menu_Items_Equipment_Weapon = Gui_Menu_Items_Equipment + ".weapon",
            Gui_Menu_Items_Equipment_Shotlock = Gui_Menu_Items_Equipment + ".shotlock",
            Gui_Menu_Items_Equipment_Accessories = Gui_Menu_Items_Equipment + ".accessories",
            Gui_Menu_Items_Equipment_Armor = Gui_Menu_Items_Equipment + ".armor",
            Gui_Menu_Items_Equipment_Magic = Gui_Menu_Items_Equipment + ".magic",
            Gui_Menu_Items_Equipment_Pauldron = Gui_Menu_Items_Equipment + ".pauldron",
            Gui_Menu_Items_Equipment_Items = Gui_Menu_Items_Equipment + ".items",

            Gui_Menu_Items_Equipment_Weapon_Keyblades = Gui_Menu_Items_Equipment_Weapon + ".keyblades",
            
            Gui_Menu_Customize = Gui_Menu + ".customize",

			Gui_Menu_Customize_Shortcuts = Gui_Menu_Customize + ".shortcuts",
			Gui_Menu_Customize_Magic = Gui_Menu_Customize + ".magic",

            Gui_Menu_Party = Gui_Menu + ".party",
            Gui_Menu_Party_Create = Gui_Menu_Party + ".create",
            Gui_Menu_Party_Create_Name = Gui_Menu_Party_Create + ".name",
            Gui_Menu_Party_Create_Accessibility = Gui_Menu_Party_Create + ".accessibility",
            Gui_Menu_Party_Create_Accessibility_Public = Gui_Menu_Party_Create_Accessibility + ".public",
            Gui_Menu_Party_Create_Accessibility_Private = Gui_Menu_Party_Create_Accessibility + ".private",
            Gui_Menu_Party_Leader_Invite = Gui_Menu_Party+".invite",
			Gui_Menu_Party_Leader_Settings = Gui_Menu_Party+".settings",
			Gui_Menu_Party_Leader_Promote = Gui_Menu_Party+".promote",
			Gui_Menu_Party_Leader_Kick = Gui_Menu_Party+".kick",
			Gui_Menu_Party_Leader_Disband = Gui_Menu_Party+".disband",
			Gui_Menu_Party_Member_Leave = Gui_Menu_Party+".leave",
            
            Gui_Menu_Party_Join = Gui_Menu_Party + ".join",

            Gui_Menu_Struggle = Gui_Menu + ".struggle",
            Gui_Menu_Struggle_Menu_Title = Gui_Menu_Struggle + ".menu_title",
            Gui_Menu_Struggle_Create_Title = Gui_Menu_Struggle + ".create_title",
            Gui_Menu_Struggle_Join_Title = Gui_Menu_Struggle + ".join_title",
            Gui_Menu_Struggle_Settings_Title = Gui_Menu_Struggle + ".settings_title",
            Gui_Menu_Struggle_Create_Button = Gui_Menu_Struggle + ".create_button",
            Gui_Menu_Struggle_Join_Button = Gui_Menu_Struggle + ".join_button",
            Gui_Menu_Struggle_Settings_Button = Gui_Menu_Struggle + ".settings_button",
            Gui_Menu_Struggle_Delete_Button = Gui_Menu_Struggle + ".delete_button",
            Gui_Menu_Struggle_Leave_Button = Gui_Menu_Struggle + ".leave_button",
            Gui_Menu_Struggle_Ready = Gui_Menu_Struggle + ".ready",
            Gui_Menu_Struggle_Cancel_Ready = Gui_Menu_Struggle + ".cancel_ready",
            Gui_Menu_Struggle_Reason_Not_Configured = Gui_Menu_Struggle + ".reason_not_configured",
            Gui_Menu_Struggle_Reason_Waiting = Gui_Menu_Struggle + ".reason_waiting",
            Gui_Menu_Struggle_Name_And_Size = Gui_Menu_Struggle + ".name_and_size",
            Gui_Menu_Struggle_Name = Gui_Menu_Struggle + ".name",
            Gui_Menu_Struggle_Damage_Mult = Gui_Menu_Struggle + ".damage_mult",
            Gui_Menu_Struggle_Round_Time = Gui_Menu_Struggle + ".round_time",
            Gui_Menu_Struggle_Starting_Score = Gui_Menu_Struggle + ".starting_score",
            Gui_Menu_Struggle_Corners_Pos = Gui_Menu_Struggle + ".corners_pos",
            Gui_Menu_Struggle_Spectator_Pos = Gui_Menu_Struggle + ".spectator_pos",
            Gui_Menu_Struggle_Mode = Gui_Menu_Struggle + ".mode",
            
            Gui_Menu_Status = Gui_Menu + ".status",
            Gui_Menu_Status_Title = Gui_Menu_Status + ".title",
            Gui_Menu_Status_Choice = Gui_Menu_Status + ".choice",
            Gui_Menu_Status_Level = Gui_Menu_Status + ".level",
            Gui_Menu_Status_TotalExp = Gui_Menu_Status + ".totalexp",
			Gui_Menu_Status_NextLevel = Gui_Menu_Status + ".nextlevel",
			Gui_Menu_Status_HP = Gui_Menu_Status + ".hp",
			Gui_Menu_Status_MP = Gui_Menu_Status + ".mp",
			Gui_Menu_Status_AP = Gui_Menu_Status + ".ap",
			Gui_Menu_Status_DriveGauge = Gui_Menu_Status + ".drivegauge",
			Gui_Menu_Status_Strength = Gui_Menu_Status + ".strength",
			Gui_Menu_Status_Magic = Gui_Menu_Status + ".magic",
			Gui_Menu_Status_Defense = Gui_Menu_Status + ".defense",
			Gui_Menu_Status_FireRes = Gui_Menu_Status + ".fireres",
			Gui_Menu_Status_BlizzardRes = Gui_Menu_Status + ".blizzardres",
			Gui_Menu_Status_ThunderRes = Gui_Menu_Status + ".thunderres",
			Gui_Menu_Status_AirRes = Gui_Menu_Status + ".airres",
			Gui_Menu_Status_LightRes = Gui_Menu_Status + ".lightres",
			Gui_Menu_Status_WaterRes = Gui_Menu_Status + ".waterres",
			Gui_Menu_Status_DarkRes = Gui_Menu_Status + ".darkres",
			Gui_Menu_Status_FireResShort = Gui_Menu_Status + ".fireresshort",
			Gui_Menu_Status_BlizzardResShort = Gui_Menu_Status + ".blizzardresshort",
			Gui_Menu_Status_ThunderResShort = Gui_Menu_Status + ".thunderresshort",
			Gui_Menu_Status_LightResShort = Gui_Menu_Status + ".lightresshort",
			Gui_Menu_Status_WaterResShort = Gui_Menu_Status + ".waterresshort",
			Gui_Menu_Status_AirResShort = Gui_Menu_Status + ".airresshort",
			Gui_Menu_Status_DarkResShort = Gui_Menu_Status + ".darkresshort",
			Gui_Menu_Status_FormLevel = Gui_Menu_Status + ".formlevel",
			Gui_Menu_Status_FormGauge = Gui_Menu_Status + ".formgauge",
			Gui_Menu_Status_Abilities = Gui_Menu_Status + ".abilities",
			Gui_Menu_Status_Ability = Gui_Menu_Status + ".ability",
			Gui_Menu_Status_Button = Gui_Menu_Status + ".button",

			Gui_Menu_Journal = Gui_Menu + ".journal",

            
            Gui_Menu_Config = Gui_Menu + ".config",
			Gui_Menu_Style = Gui_Menu + ".style",
            Gui_Menu_Config_Title = Gui_Menu_Config + ".title",
            Gui_Menu_Config_Colour = Gui_Menu_Config + ".colour",
            Gui_Menu_Config_Colour_Desc = Gui_Menu_Config_Colour + ".desc",
            Gui_Menu_Config_Hearts = Gui_Menu_Config + ".hearts",
            Gui_Menu_Config_Music = Gui_Menu_Config + ".music",
            Gui_Menu_Config_Fire = Gui_Menu_Config + ".fire",

            // Shop
            Gui_Shop = "gui.shop",
            Gui_Shop_Page = Gui_Shop + ".page",
	    	Gui_Shop_Tier = Gui_Shop + ".tier",
            Gui_Shop_Main = Gui_Shop + ".main",
            Gui_Shop_NoSpace = Gui_Shop + ".no_empty_slot",
            Gui_Shop_Main_Title = Gui_Shop_Main + ".title",
            Gui_Shop_Main_Buy = Gui_Shop_Main + ".buy",
            Gui_Shop_Main_Sell = Gui_Shop_Main + ".sell",
            Gui_Shop_Buy = Gui_Shop + ".buy",
            Gui_Shop_Buy_Cost = Gui_Shop + ".cost",
            Gui_Shop_Buy_Price = Gui_Shop + ".price",
            Gui_Shop_Buy_Quantity = Gui_Shop_Buy + ".quantity",
            Gui_Shop_Sell = Gui_Shop + ".sell",

			// Melding
			Gui_Menu_Items_Melding = "gui.melding",
			Gui_Menu_Items_Melding_Meld = Gui_Menu_Items_Melding + ".meld",
			Gui_Menu_Items_Melding_Meldables = Gui_Menu_Items_Melding + ".meldables",
			Gui_Menu_Items_Melding_ItemAcquired = Gui_Menu_Items_Melding+ ".item_acquired",
			Gui_Menu_Items_Melding_RareItemAcquired = Gui_Menu_Items_Melding+ ".rare_item_acquired",

			// Card packs
			Gui_CardPack_Title ="gui.cardpacks.title",

            // Synthesis
            Gui_Synthesis = "gui.synthesis",
			Gui_Synthesis_Exp = Gui_Synthesis + ".exp",
			Gui_Synthesis_Exp_MoogleLevel = Gui_Synthesis_Exp + ".mooglelevel",
			Gui_Synthesis_Exp_NextLevel = Gui_Synthesis_Exp + ".nextlevel",

			Gui_Synthesis_Main = Gui_Synthesis + ".main",
            Gui_Synthesis_Main_Title = Gui_Synthesis_Main + ".title",
            Gui_Synthesis_Main_Recipes = Gui_Synthesis_Main + ".recipes",
            Gui_Synthesis_Main_FreeDev = Gui_Synthesis_Main + ".freedevelopment",
            
            Gui_Synthesis_Synthesise = Gui_Synthesis + ".synthesise",
	    	Gui_Synthesis_Synthesise_Title = Gui_Synthesis_Synthesise + ".title",
            Gui_Synthesis_Synthesise_Create = Gui_Synthesis_Synthesise + ".create",
            
            Gui_Synthesis_Forge = Gui_Synthesis + ".forge",
	    	Gui_Synthesis_Forge_Title = Gui_Synthesis_Forge + ".title",
            Gui_Synthesis_Forge_Upgrade = Gui_Synthesis_Forge + ".upgrade",
            
            Gui_Synthesis_Materials = Gui_Synthesis + ".materials",
            Gui_Synthesis_Materials_Deposit = Gui_Synthesis_Materials + ".deposit",
            Gui_Synthesis_Materials_Take = Gui_Synthesis_Materials + ".take",
            Gui_Synthesis_Main_Materials_Deposit_Inv = Gui_Synthesis_Materials_Deposit + ".inventory",
            Gui_Synthesis_Main_Materials_Deposit_Bag = Gui_Synthesis_Materials_Deposit + ".bag",
            Gui_Synthesis_Main_Materials_TakeOne = Gui_Synthesis_Materials + ".takeone",
            Gui_Synthesis_Main_Materials_TakeHalfStack = Gui_Synthesis_Materials + ".takehalfstack",
            Gui_Synthesis_Main_Materials_TakeStack = Gui_Synthesis_Materials + ".takestack",
            Gui_Synthesis_Main_Materials_TakeAll = Gui_Synthesis_Materials + ".takeall",
            Gui_Synthesis_Main_Recipes_ReqMaterials = Gui_Synthesis_Main_Recipes + ".requiredmaterials",
            Gui_Synthesis_Main_Recipes_Create = Gui_Synthesis_Main_Recipes + ".create",

			Gui_Synthesis_Moogle_Name = "gui.synthesis.moogle.title",

			//Save Points
			Gui_Save = "gui.save",
			Gui_Save_Creation = Gui_Save + ".create",
			Gui_Save_Creation_Title = Gui_Save_Creation + ".title",
			Gui_Save_Creation_Prompt = Gui_Save_Creation + ".prompt",
			Gui_Save_Creation_Global = Gui_Save_Creation + ".global",
			Gui_Save_Creation_Global_Desc = Gui_Save_Creation_Global + ".desc",
			Gui_Save_Creation_Accept = Gui_Save_Creation + ".accept",

			Gui_Save_Main = Gui_Save + ".main",
			Gui_Save_Main_CurrentPosition = Gui_Save_Main + ".here",
			Gui_Save_Main_Sort = Gui_Save_Main + ".sort",
			Gui_Save_Main_Rename = Gui_Save_Main + ".rename",
			Gui_Save_Main_Retake = Gui_Save_Main + ".retake",

			Gui_Save_Sorting = Gui_Save + ".sort",
			Gui_Save_Sorting_ByRecent = Gui_Save_Sorting + ".recent",
			Gui_Save_Sorting_ByName = Gui_Save_Sorting + ".name",
			Gui_Save_Sorting_ByDimension = Gui_Save_Sorting + ".dimension",
			Gui_Save_Sorting_ByOwner = Gui_Save_Sorting + ".owner",
			Gui_Save_Sorting_Ascending = Gui_Save_Sorting + ".ascending",
			Gui_Save_Sorting_Descending = Gui_Save_Sorting + ".descending",

			//KO Screen
			Gui_KO = "gui.ko",
			Gui_KO_Die = Gui_KO + ".give_up",
			Gui_KO_Quit = Gui_KO + ".exit",

			//Item get
			Gui_ItemGet_Obtained = "gui.itemget.obtained",
			Gui_ItemGet_Dismiss = "gui.itemget.dismiss";


	//Items

    public static final String
        iceCream = "ice_cream",
        winnerStick = "winner_stick",
        trainingDummy = "training_dummy",
        potion = "potion",
        hiPotion = "hi_potion",
        megaPotion = "mega_potion",
		ether = "ether",
        hiEther = "hi_ether",
        megaEther = "mega_ether",
        elixir = "elixir",
        megaLixir = "mega_lixir",
        refocuser = "refocuser",
        hiRefocuser = "hi_refocuser",
        driveRecovery = "drive_recovery",   
        hiDriveRecovery = "hi_drive_recovery",
        panacea = "panacea",
        
        synthesisBag = "synthesis_bag",

		SpellFire = "spellfire",
		SpellFira = "spellfira",
		SpellFiraga = "spellfiraga",

		SpellBlizzard = "spellblizzard",
		SpellBlizzara = "spellblizzara",
		SpellBlizzaga = "spellblizzaga",

		SpellWater = "spellwater",
		SpellWatera = "spellwatera",
		SpellWaterga = "spellwaterga",

		SpellThunder = "spellthunder",
		SpellThundara = "spellthundara",
		SpellThundaga = "spellthundaga",

		SpellCure = "spellcure",
		SpellCura = "spellcura",
		SpellCuraga = "spellcuraga",

		// The plain names stay with the twister, so a spell already sitting in a chest teaches the new one
		SpellAero = "spellaero",
		SpellAerora = "spellaerora",
		SpellAeroga = "spellaeroga",

		SpellAeroShield = "spellaeroshield",
		SpellAeroraShield = "spellaerorashield",
		SpellAerogaShield = "spellaerogashield",

		SpellMagnet = "spellmagnet",
		SpellMagnera = "spellmagnera",
		SpellMagnega = "spellmagnega",

		SpellReflect = "spellreflect",
		SpellReflera = "spellreflera",
		SpellReflega = "spellreflega",

		SpellGravity = "spellgravity",
		SpellGravira = "spellgravira",
		SpellGraviga = "spellgraviga",

		SpellZeroGravity = "spellzerogravity",
		SpellZeroGravira = "spellzerogravira",
		SpellZeroGraviga = "spellzerograviga",

		SpellStop = "spellstop",
		SpellStopra = "spellstopra",
		SpellStopga = "spellstopga",

		SpellDarkFiraga = "spelldarkfiraga",
		SpellTripleFiraga = "spelltriplefiraga",
		SpellBlackout = "spellblackout",
		SpellPoison = "spellpoison",
		SpellCrawlingFiraga = "spellcrawlingfiraga",
		SpellFissionFiraga = "spellfissionfiraga",
		SpellFiragaBurst = "spellfiragaburst",
		SpellIgnite = "spellignite",

		SpellTripleBlizzaga = "spelltripleblizzaga",
		SpellDeepFreeze = "spelldeepfreeze",
		SpellGlacier = "spellglacier",
		SpellIceBarrage = "spellicebarrage",

		SpellThundagaShot = "spellthundagashot",
		SpellTriplePlasma = "spelltripleplasma",

		SpellBalloon = "spellballoon",
		SpellBalloonra = "spellballoonra",
		SpellBalloonga = "spellballoonga",

		SpellMineShield = "spellmineshield",
		SpellMineSquare = "spellminesquare",
		SpellMineSeeker = "spellseekermine",

		SpellSpark = "spellspark",
		SpellSparkra = "spellsparkra",
		SpellSparkga = "spellsparkga",

		SpellWarp = "spellwarp",
		SpellFaith = "spellfaith",

		SpellEsuna = "spellesuna",
		SpellConfuse = "spellconfuse",
		SpellBind = "spellbind",
		SpellMini = "spellmini",
		SpellSlow = "spellslow",


		StruggleSword = "struggle_sword",
		StruggleWand = "struggle_wand",
		StruggleHammer = "struggle_hammer",
        
        LevelUpValor = "levelupdrivevalor",
        LevelUpWisdom = "levelupdrivewisdom",
        LevelUpLimit = "levelupdrivelimit",
        LevelUpMaster = "levelupdrivemaster",
        LevelUpFinal = "levelupdrivefinal",
        
        wayfinder = "wayfinder",
        gummiPhone = "gummiphone",
		gummiShipBlueprint = "gummi_ship_blueprint",
		gummiShipBlueprintCreative = "gummi_ship_blueprint_creative",
        
        powerBoost = "powerboost",
        magicBoost = "magicboost",
        defenseBoost = "defenseboost",
        apBoost = "apboost",
        
        abilityRing = "ability_ring",
        aquamarineRing = "aquamarine_ring",
		cosmicArts = "cosmic_arts",
		executiveRing = "executive_ring",
		fullBloom = "full_bloom",
		fullBloomPlus = "full_bloom_plus",
		shadowArchive = "shadow_archive",
		shadowArchivePlus = "shadow_archive_plus",
		drawRing = "draw_ring",
		luckyRing = "lucky_ring",
		starCharm = "star_charm",
		fireBangle = "fire_bangle",
	    blizzardArmlet = "blizzard_armlet",
	    thunderTrinket = "thunder_trinket",
    	petiteRibbon = "petite_ribbon",
    	ribbon = "ribbon",
    	grandRibbon = "grand_ribbon",

		engineersRing = "engineers_ring",
		techniciansRing = "technicians_ring",
		skillRing = "skill_ring",
		skillfulRing = "skillful_ring",
		expertsRing = "experts_ring",
		mastersRing = "masters_ring",
		cosmicRing = "cosmic_ring",
		sardonyxRing = "sardonyx_ring",
		goldRing = "gold_ring",
		garnetRing = "garnet_ring",
		diamondRing = "diamond_ring",
		silverRing = "silver_ring",
		tourmalineRing = "tourmaline_ring",
		platinumRing = "platinum_ring",
		mythrilRing = "mythril_ring",
		orichalcumRing = "orichalcum_ring",
		medal = "medal",
		soldierEarring = "soldier_earring",
		mageEarring = "mage_earring",
		moonAmulet = "moon_amulet",
		slayerEarring = "slayer_earring",
		fencerEarring = "fencer_earring",


		abasChain = "abas_chain",
		acrisius = "acrisius",
		acrisiusPlus = "acrisius_plus",
		aegisChain = "aegis_chain",
		blizzagaArmlet = "blizzaga_armlet",
		blizzagunArmlet = "blizzagun_armlet",
		blizzaraArmlet = "blizzara_armlet",
		powerBand = "power_band",
		busterBand = "buster_band",
		championBelt = "champion_belt",
		chaosAnklet = "chaos_anklet",
		cosmicBelt = "cosmic_belt",
		cosmicChain = "cosmic_chain",
		darkAnklet = "dark_anklet",
		divineBandanna = "divine_bandanna",
		elvenBandanna = "elven_bandanna",
		firaBangle = "fira_bangle",
		firagaBangle = "firaga_bangle",
		firagunBangle = "firagun_bangle",
		protectBelt = "protect_belt",
		gaiaBelt = "gaia_belt",
		lightDefTest = "light_def_test",
		midnightAnklet = "midnight_anklet",
		shadowAnklet = "shadow_anklet",
		shockCharm = "shock_charm",
		shockCharmPlus = "shock_charm_plus",
		thundaraTrinket = "thundara_trinket",
		thundagaTrinket = "thundaga_trinket",
		thundagunTrinket = "thundagun_trinket";
    	
    
    // Music Discs
    public static final String
	    Disc_Birth_by_Sleep_A_Link_to_the_Future = "disc_0",
	    Disc_Dearly_Beloved_UX = "disc_1",
	    Disc_Passion_Instrumental = "disc_2",
	    Disc_Dream_Drop_Distance_The_Next_Awakening = "disc_3",
	    Disc_Hikari_KINGDOM_Instrumental_Version = "disc_4",
	    Disc_L_Oscurita_Dell_Ignoto = "disc_5",
	    Disc_Musique_pour_la_tristesse_de_Xion = "disc_6",
	    Disc_No_More_Bugs_Bug_Version = "disc_7",
	    Disc_Organization_XIII = "disc_8",
	    Disc_Rage_Awakened = "disc_9",
	    Disc_The_Other_Promise = "disc_10",
	    Disc_13th_Struggle_Luxord = "disc_11",
	    Disc_13th_Dilemma_Saix = "disc_12",
	    Disc_13th_Reflection = "disc_13",
		Disc_Another_Side_Battle_Ver = "disc_14",
		Disc_Cavern_Of_Remembrance_Days = "disc_15",
		Disc_Forgotten_Challenge_Recoded = "disc_16",
		Disc_Anger_Unchained = "disc_17",
		Disc_Hunter_Of_The_Dark = "disc_18",
		Disc_Destati = "disc_19"		
    ;

    //Keyblades
    public static final String
        abaddonPlasma = "abaddon_plasma",
        abyssalTide = "abyssal_tide",
        acedsKeyblade = "aceds_keyblade",
		adventRed = "advent_red",
        allForOne = "all_for_one",
        astralBlast = "astral_blast",
        aubade = "aubade",
        avasKeyblade = "avas_keyblade",
        bondOfFlame = "bond_of_flame",
        bondOfTheBlaze = "bond_of_the_blaze",
		braveheart = "braveheart",
        brightcrest = "brightcrest",
        chaosRipper = "chaos_ripper",
        circleOfLife = "circle_of_life",
        classicTone = "classic_tone",
        counterpoint = "counterpoint",
        crabclaw = "crabclaw",
        crownOfGuilt = "crown_of_guilt",
        crystalSnow = "crystal_snow",
        darkerThanDark = "darker_than_dark",
        darkgnaw = "darkgnaw",
		dawnTillDusk = "dawn_till_dusk",
		deadOfNight = "dead_of_night",
        decisivePumpkin = "decisive_pumpkin",
        destinysEmbrace = "destinys_embrace",
        diamondDust = "diamond_dust",
        divewing = "divewing",
        divineRose = "divine_rose",
        dreamShield = "dream_shield",
        dreamStaff = "dream_staff",
        dreamSword = "dream_sword",
        dualDisc = "dual_disc",
        earthshaker = "earthshaker",
		elementalEncoder = "elemental_encoder",
        endOfPain = "end_of_pain",
        endsOfTheEarth = "ends_of_the_earth",
        everAfter= "ever_after",
        fairyHarp = "fairy_harp",
        fairyStars = "fairy_stars",
        fatalCrest = "fatal_crest",
        favoriteDeputy = "favorite_deputy",
        fenrir = "fenrir",
        ferrisGear = "ferris_gear",
        followTheWind = "follow_the_wind",
        frolicFlame = "frolic_flame",
        glimpseOfDarkness = "glimpse_of_darkness",
        grandChef = "grand_chef",
        guardianBell = "guardian_bell",
        guardianSoul = "guardian_soul",
        gulasKeyblade = "gulas_keyblade",
        gullWing = "gull_wing",
        happyGear = "happy_gear",
        herosCrest = "heros_crest",
		herosOrigin = "heros_origin",
        hiddenDragon = "hidden_dragon",
        hunnySpout = "hunny_spout",
        hyperdrive = "hyperdrive",
        incompleteKiblade = "incomplete_kiblade",
        invisKeyblade = "invis_keyblade",
        irasKeyblade = "iras_keyblade",
        jungleKing = "jungle_king",
        keybladeOfPeoplesHearts = "keyblade_of_peoples_hearts",
        kiblade = "kiblade",
        kingdomKey = "kingdom_key",
        kingdomKeyD = "kingdom_key_d",
        kingdomKeyN = "kingdom_key_n",
        knockoutPunch = "knockout_punch",
        ladyLuck = "lady_luck",
        leviathan = "leviathan",
        lionheart = "lionheart",
        longNight = "long_night",
        lostMemory = "lost_memory",
        lunarEclipse = "lunar_eclipse",
        markOfAHero = "mark_of_a_hero",
        mastersDefender = "masters_defender",
        maverickFlare = "maverick_flare",
        metalChocobo = "metal_chocobo",
		midnightBlue = "midnight_blue",
        midnightRoar = "midnight_roar",
        mirageSplit = "mirage_split",
        missingAche = "missing_ache",
        monochrome = "monochrome",
        moogleOGlory = "moogle_o_glory",
        mysteriousAbyss = "mysterious_abyss",
		nanoGear = "nano_gear",
        nightmaresEnd = "nightmares_end",
        nightmaresEndAndMirageSplit = "nightmares_end_and_mirage_split",
        noName = "no_name",
        noNameBBS = "no_name_bbs",
        oathkeeper = "oathkeeper",
        oblivion = "oblivion",
        oceansRage = "oceans_rage",
        olympia = "olympia",
        omegaWeapon = "omega_weapon",
        ominousBlight = "ominous_blight",
        oneWingedAngel = "one_winged_angel",
        painOfSolitude = "pain_of_solitude",
		phantomGreen = "phantom_green",
        photonDebugger = "photon_debugger",
        pixiePetal = "pixie_petal",
        pumpkinhead = "pumpkinhead",
        rainfell = "rainfell",
        rejectionOfFate = "rejection_of_fate",
        royalRadiance = "royal_radiance",
        rumblingRose = "rumbling_rose",
        shootingStar = "shooting_star",
        signOfInnocence = "sign_of_innocence",
        silentDirge = "silent_dirge",
        skullNoise = "skull_noise",
        sleepingLion = "sleeping_lion",
        soulEater = "soul_eater",
        spellbinder = "spellbinder",
		starCluster = "star_cluster",
        starSeeker = "star_seeker",
        starlight = "starlight",
        stormfall = "stormfall",
        strokeOfMidnight = "stroke_of_midnight",
        sweetDreams = "sweet_dreams",
        sweetMemories = "sweet_memories",
        sweetstack = "sweetstack",
        threeWishes = "three_wishes",
        totalEclipse = "total_eclipse",
        treasureTrove = "treasure_trove",
        trueLightsFlight = "true_lights_flight",
        twilightBlaze = "twilight_blaze",
        twoBecomeOne = "two_become_one",
        ultimaWeaponBBS = "ultima_weapon_bbs",
        ultimaWeaponDDD = "ultima_weapon_ddd",
        ultimaWeaponKH1 = "ultima_weapon_kh1",
        ultimaWeaponKH2 = "ultima_weapon_kh2",
        ultimaWeaponKH3 = "ultima_weapon_kh3",
        umbrella = "umbrella",
        unbound = "unbound",
        victoryLine = "victory_line",
        voidGear = "void_gear",
        voidGearRemnant = "void_gear_remnant",
        wayToTheDawn = "way_to_the_dawn",
        waywardWind = "wayward_wind",
        wheelOfFate = "wheel_of_fate",
        winnersProof = "winners_proof",
        wishingLamp = "wishing_lamp",
        wishingStar = "wishing_star",
        woodenKeyblade = "wooden_keyblade",
        woodenStick = "wooden_stick",
        youngXehanortsKeyblade = "young_xehanorts_keyblade",
        zeroOne = "zero_one",
		k111 = "k111",
		retribution = "retribution"
	;

    //Keychains
    public static final String
        abaddonPlasmaChain = "abaddon_plasma_chain",
        abyssalTideChain = "abyssal_tide_chain",
        acedsKeybladeChain = "aceds_keyblade_chain",
		adventRedChain = "advent_red_chain",
        allForOneChain = "all_for_one_chain",
        astralBlastChain = "astral_blast_chain",
        aubadeChain = "aubade_chain",
        avasKeybladeChain = "avas_keyblade_chain",
        bondOfFlameChain = "bond_of_flame_chain",
        bondOfTheBlazeChain = "bond_of_the_blaze_chain",
		braveheartChain = "braveheart_chain",
        brightcrestChain = "brightcrest_chain",
        chaosRipperChain = "chaos_ripper_chain",
        circleOfLifeChain = "circle_of_life_chain",
        classicToneChain = "classic_tone_chain",
        counterpointChain = "counterpoint_chain",
        crabclawChain = "crabclaw_chain",
        crownOfGuiltChain = "crown_of_guilt_chain",
        crystalSnowChain = "crystal_snow_chain",
        darkerThanDarkChain = "darker_than_dark_chain",
        darkgnawChain = "darkgnaw_chain",
		dawnTillDuskChain = "dawn_till_dusk_chain",
		deadOfNightChain = "dead_of_night_chain",
        decisivePumpkinChain = "decisive_pumpkin_chain",
        destinysEmbraceChain = "destinys_embrace_chain",
        diamondDustChain = "diamond_dust_chain",
        divewingChain = "divewing_chain",
        divineRoseChain = "divine_rose_chain",
        dualDiscChain = "dual_disc_chain",
        earthshakerChain = "earthshaker_chain",
		elementalEncoderChain = "elemental_encoder_chain",
        endOfPainChain = "end_of_pain_chain",
        endsOfTheEarthChain = "ends_of_the_earth_chain",
        everAfterChain = "ever_after_chain",
        fairyHarpChain = "fairy_harp_chain",
        fairyStarsChain = "fairy_stars_chain",
        fatalCrestChain = "fatal_crest_chain",
        favoriteDeputyChain = "favorite_deputy_chain",
        fenrirChain = "fenrir_chain",
        ferrisGearChain = "ferris_gear_chain",
        followTheWindChain = "follow_the_wind_chain",
        frolicFlameChain = "frolic_flame_chain",
        glimpseOfDarknessChain = "glimpse_of_darkness_chain",
        grandChefChain = "grand_chef_chain",
        guardianBellChain = "guardian_bell_chain",
        guardianSoulChain = "guardian_soul_chain",
        gulasKeybladeChain = "gulas_keyblade_chain",
        gullWingChain = "gull_wing_chain",
        happyGearChain = "happy_gear_chain",
        herosCrestChain = "heros_crest_chain",
		herosOriginChain = "heros_origin_chain",
        hiddenDragonChain = "hidden_dragon_chain",
        hunnySpoutChain = "hunny_spout_chain",
        hyperdriveChain = "hyperdrive_chain",
        incompleteKibladeChain = "incomplete_kiblade_chain",
        invisKeybladeChain = "invis_keyblade_chain",
        irasKeybladeChain = "iras_keyblade_chain",
        jungleKingChain = "jungle_king_chain",
        keybladeOfPeoplesHeartsChain = "keyblade_of_peoples_hearts_chain",
        kibladeChain = "kiblade_chain",
        kingdomKeyChain = "kingdom_key_chain",
        kingdomKeyDChain = "kingdom_key_d_chain",
        kingdomKeyNChain = "kingdom_key_n_chain",
        knockoutPunchChain = "knockout_punch_chain",
        ladyLuckChain = "lady_luck_chain",
        leviathanChain = "leviathan_chain",
        lionheartChain = "lionheart_chain",
        longNightChain = "long_night_chain",
        lostMemoryChain = "lost_memory_chain",
        lunarEclipseChain = "lunar_eclipse_chain",
        markOfAHeroChain = "mark_of_a_hero_chain",
        mastersDefenderChain = "masters_defender_chain",
        maverickFlareChain = "maverick_flare_chain",
        metalChocoboChain = "metal_chocobo_chain",
		midnightBlueChain = "midnight_blue_chain",
        midnightRoarChain = "midnight_roar_chain",
        mirageSplitChain = "mirage_split_chain",
        missingAcheChain = "missing_ache_chain",
        monochromeChain = "monochrome_chain",
        moogleOGloryChain = "moogle_o_glory_chain",
        mysteriousAbyssChain = "mysterious_abyss_chain",
		nanoGearChain = "nano_gear_chain",
        nightmaresEndChain = "nightmares_end_chain",
        nightmaresEndAndMirageSplitChain = "nightmares_end_and_mirage_split_chain",
        noNameChain = "no_name_chain",
        noNameBBSChain = "no_name_bbs_chain",
        oathkeeperChain = "oathkeeper_chain",
        oblivionChain = "oblivion_chain",
        oceansRageChain = "oceans_rage_chain",
        olympiaChain = "olympia_chain",
        omegaWeaponChain = "omega_weapon_chain",
        ominousBlightChain = "ominous_blight_chain",
        oneWingedAngelChain = "one_winged_angel_chain",
        painOfSolitudeChain = "pain_of_solitude_chain",
		phantomGreenChain = "phantom_green_chain",
        photonDebuggerChain = "photon_debugger_chain",
        pixiePetalChain = "pixie_petal_chain",
        pumpkinheadChain = "pumpkinhead_chain",
        rainfellChain = "rainfell_chain",
        rejectionOfFateChain = "rejection_of_fate_chain",
        royalRadianceChain = "royal_radiance_chain",
        rumblingRoseChain = "rumbling_rose_chain",
        shootingStarChain= "shooting_star_chain",
        signOfInnocenceChain = "sign_of_innocence_chain",
        silentDirgeChain = "silent_dirge_chain",
        skullNoiseChain = "skull_noise_chain",
        sleepingLionChain = "sleeping_lion_chain",
        soulEaterChain = "soul_eater_chain",
        spellbinderChain = "spellbinder_chain",
		starClusterChain = "star_cluster_chain",
        starSeekerChain = "star_seeker_chain",
        starlightChain = "starlight_chain",
        stormfallChain = "stormfall_chain",
        strokeOfMidnightChain = "stroke_of_midnight_chain",
        sweetDreamsChain = "sweet_dreams_chain",
        sweetMemoriesChain = "sweet_memories_chain",
        sweetstackChain = "sweetstack_chain",
        threeWishesChain = "three_wishes_chain",
        totalEclipseChain = "total_eclipse_chain",
        treasureTroveChain = "treasure_trove_chain",
        trueLightsFlightChain = "true_lights_flight_chain",
        twilightBlazeChain = "twilight_blaze_chain",
        twoBecomeOneChain = "two_become_one_chain",
        ultimaWeaponBBSChain = "ultima_weapon_bbs_chain",
        ultimaWeaponDDDChain = "ultima_weapon_ddd_chain",
        ultimaWeaponKH1Chain = "ultima_weapon_kh1_chain",
        ultimaWeaponKH2Chain = "ultima_weapon_kh2_chain",
        ultimaWeaponKH3Chain = "ultima_weapon_kh3_chain",
        umbrellaChain = "umbrella_chain",
        unboundChain = "unbound_chain",
        victoryLineChain = "victory_line_chain",
        voidGearChain = "void_gear_chain",
        voidGearRemnantChain = "void_gear_remnant_chain",
        wayToTheDawnChain = "way_to_the_dawn_chain",
        waywardWindChain = "wayward_wind_chain",
        wheelOfFateChain = "wheel_of_fate_chain",
        winnersProofChain = "winners_proof_chain",
        wishingLampChain = "wishing_lamp_chain",
        wishingStarChain = "wishing_star_chain",
        youngXehanortsKeybladeChain = "young_xehanorts_keyblade_chain",
        zeroOneChain = "zero_one_chain",

		k111c = "k111c",
		retributionChain = "retribution_chain"
	;

    //Misc
    public static final String
    	recipe = "recipe",
        proofOfHeart = "proof_of_heart"
    ;

    //Organization
    //Xemnas
    public static final String
        malice = "malice",
        sanction = "sanction",
        overlord = "overlord",
        veneration = "veneration",
        autocracy = "autocracy",
        conquest = "conquest",
        terminus = "terminus",
        judgement = "judgement",
        discipline = "discipline",
        aristocracy = "aristocracy",
        superiority = "superiority",
        aggression = "aggression",
        fury = "fury",
        despair = "despair",
        triumph = "triumph",
        ruination = "ruination",
        domination = "domination",
        annihilation = "annihilation",
        tyrant = "tyrant",
        magnificence = "magnificence",
        infinity = "infinity",
        interdiction = "interdiction",
        roundFan = "round_fan",
        absolute = "absolute";
    //Xigbar
    public static final String
            standalone = "standalone",
            killerbee = "killerbee",
            stingray = "stingray",
            counterweight = "counterweight",
            precision = "precision",
            dualHead = "dual_head",
            bahamut = "bahamut",
            gullwing = "gullwing",
            blueFrame = "blue_frame",
            starShell = "star_shell",
            sunrise = "sunrise",
            ignition = "ignition",
            armstrong = "armstrong",
            hardBoiledHeat = "hard_boiled_heat",
            diabloEye = "diablo_eye",
            doubleTap = "double_tap",
            stardust = "stardust",
            energyMuzzle = "energy_muzzle",
            crimeAndPunishment = "crime_and_punishment",
            cupidsArrow = "cupids_arrow",
            finalWeapon = "final_weapon",
            sharpshooter = "sharpshooter",
            dryer = "dryer",
            trumpet = "trumpet";
    //Xaldin
    public static final String
            zephyr = "zephyr",
            moonglade = "moonglade",
            aer = "aer",
            nescience = "nescience",
            brume = "brume",
            asura = "asura",
            crux = "crux",
            paladin = "paladin",
            fellking = "fellking",
            nightcloud = "nightcloud",
            shimmer = "shimmer",
            vortex = "vortex",
            scission = "scission",
            heavenfall = "heavenfall",
            aether = "aether",
            mazzaroth = "mazzaroth",
            hegemon = "hegemon",
            foxfire = "foxfire",
            yaksha = "yaksha",
            cynosura = "cynosura",
            dragonreign = "dragonreign",
            lindworm = "lindworm",
            broom = "broom",
            wyvern = "wyvern";
    //Vexen
    public static final String
            testerZero = "tester_zero",
            productOne = "product_one",
            deepFreeze = "deep_freeze",
            cryoliteShield = "cryolite_shield",
            falseTheory = "false_theory",
            glacier = "glacier",
            absoluteZero = "absolute_zero",
            gunz = "gunz",
            mindel = "mindel",
            snowslide = "snowslide",
            iceberg = "iceberg",
            inquisition = "inquisition",
            scrutiny = "scrutiny",
            empiricism = "empiricism",
            edification = "edification",
            contrivance = "contrivance",
            wurm = "wurm",
            subzero = "subzero",
            coldBlood = "cold_blood",
            diamondShield = "diamond_shield",
            aegis = "aegis",
            frozenPride = "frozen_pride",
            potLid = "pot_lid",
            snowman = "snowman";
    //Lexaeus
    public static final String
            reticence = "reticence",
            goliath = "goliath",
            copperRed = "copper_red",
            daybreak = "daybreak",
            colossus = "colossus",
            ursaMajor = "ursa_major",
            megacosm = "megacosm",
            terrene = "terrene",
            fuligin = "fuligin",
            hardWinter = "hard_winter",
            firefly = "firefly",
            harbinger = "harbinger",
            redwood = "redwood",
            sequoia = "sequoia",
            ironBlack = "iron_black",
            earthshine = "earthshine",
            octiron = "octiron",
            hyperion = "hyperion",
            clarity = "clarity",
            oneThousandAndOneNights = "one_thousand_and_one_nights",
            cardinalVirtue = "cardinal_virtue",
            skysplitter = "skysplitter",
            bleepBloopBop = "bleep_bloop_bop",
            monolith = "monolith";
    //Zexion
    public static final String
            blackPrimer = "black_primer",
            whiteTome = "white_tome",
            illicitResearch = "illicit_research",
            buriedSecrets = "buried_secrets",
            arcaneCompendium = "arcane_compendium",
            dissentersNotes = "dissenters_notes",
            nefariousCodex = "nefarious_codex",
            mysticAlbum = "mystic_album",
            cursedManual = "cursed_manual",
            tabooText = "taboo_text",
            eldritchEsoterica = "eldritch_esoterica",
            freakishBestiary = "freakish_bestiary",
            madmansVita = "madmans_vita",
            untitledWritings = "untitled_writings",
            abandonedDogma = "abandoned_dogma",
            atlasOfOmens = "atlas_of_omens",
            revoltingScrapbook = "revolting_scrapbook",
            lostHeterodoxy = "lost_heterodoxy",
            otherworldlyTales = "otherworldly_tales",
            indescribableLore = "indescribable_lore",
            radicalTreatise = "radical_treatise",
            bookOfRetribution = "book_of_retribution",
            midnightSnack = "midnight_snack",
            dearDiary = "dear_diary";
    //Saix
    public static final String
            newMoon = "new_moon",
            werewolf = "werewolf",
            artemis  = "artemis",
            luminary = "luminary",
            selene = "selene",
            moonrise = "moonrise",
            astrologia = "astrologia",
            crater = "crater",
            lunarPhase = "lunar_phase",
            crescent = "crescent",
            gibbous = "gibbous",
            berserker = "berserker",
            twilight = "twilight",
            queenOfTheNight = "queen_of_the_night",
            balsamicMoon = "balsamic_moon",
            orbit = "orbit",
            lightYear = "light_year",
            kingOfTheNight = "king_of_the_night",
            moonset = "moonset",
            horoscope = "horoscope",
            dichotomy = "dichotomy",
            lunatic = "lunatic",
            justDesserts = "just_desserts",
            bunnymoon = "bunnymoon";
    //Axel
    public static final String
            ashes = "ashes",
            doldrums = "doldrums",
            delayedAction = "delayed_action",
            diveBombers = "dive_bombers",
            combustion = "combustion",
            moulinRouge = "moulin_rouge",
            blazeOfGlory = "blaze_of_glory",
            prometheus = "prometheus",
            ifrit = "ifrit",
            magmaOcean = "magma_ocean",
            volcanics = "volcanics",
            inferno = "inferno",
            sizzlingEdge = "sizzling_edge",
            corona = "corona",
            ferrisWheel = "ferris_wheel",
            burnout = "burnout",
            omegaTrinity = "omega_trinity",
            outbreak = "outbreak",
            doubleEdge = "double_edge",
            wildfire = "wildfire",
            prominence = "prominence",
            eternalFlames = "eternal_flames",
            pizzaCut = "pizza_cut",
            conformers = "conformers";
    //Demyx
    public static final String
            basicModel = "basic_model",
            tuneUp = "tune_up",
            quartet = "quartet",
            quintet = "quintet",
            overture = "overture",
            oldHand = "old_hand",
            daCapo = "da_capo",
            powerChord = "power_chord",
            fermata = "fermata",
            interlude = "interlude",
            serenade = "serenade",
            songbird = "songbird",
            riseToFame = "rise_to_fame",
            rockStar = "rock_star",
            eightFinger = "eight_finger",
            concerto = "concerto",
            harmonics = "harmonics",
            millionBucks = "million_bucks",
            fortissimo = "fortissimo",
            upToEleven = "up_to_eleven",
            sanctuary = "sanctuary",
            arpeggio = "arpeggio",
            princeOfAwesome = "prince_of_awesome",
            afterSchool = "after_school";
    //Luxord
    public static final String
            theFool = "the_fool",
            theMagician = "the_magician",
            theStar = "the_star",
            theMoon = "the_moon",
            justice = "justice",
            theHierophant = "the_hierophant",
            theWorld = "the_world",
            temperance = "temperance",
            theHighPriestess = "the_high_priestess",
            theTower = "the_tower",
            theHangedMan = "the_hanged_man",
            death = "death",
            theHermit = "the_hermit",
            strength = "strength",
            theLovers = "the_lovers",
            theChariot = "the_chariot",
            theSun = "the_sun",
            theDevil = "the_devil",
            theEmpress = "the_empress",
            theEmperor = "the_emperor",
            theJoker = "the_joker",
            fairGame = "fair_game",
            finestFantasy13 = "finest_fantasy_13",
            highRollersSecret = "high_rollers_secret";
    //Marluxia
    public static final String
            fickleErica = "fickle_erica",
            jiltedAnemone = "jilted_anemone",
            proudAmaryllis = "proud_amaryllis",
            madSafflower = "mad_safflower",
            poorMelissa = "poor_melissa",
            tragicAllium = "tragic_allium",
            mournfulCineria = "mournful_cineria",
            pseudoSilene = "pseudo_silene",
            faithlessDigitalis = "faithless_digitalis",
            grimMuscari = "grim_muscari",
            docileVallota = "docile_vallota",
            quietBelladonna = "quiet_belladonna",
            partingIpheion = "parting_ipheion",
            loftyGerbera = "lofty_gerbera",
            gallantAchillea = "gallant_achillea",
            noblePeony = "noble_peony",
            fearsomeAnise = "fearsome_anise",
            vindictiveThistle = "vindictive_thistle",
            fairHelianthus = "fair_helianthus",
            solemnMagnolia = "solemn_magnolia",
            hallowedLotus ="hallowed_lotus",
            gracefulDahlia = "graceful_dahlia",
            stirringLadle = "stirring_ladle",
            daintyBellflowers = "dainty_bellflowers";
    //Larxene
    public static final String
            trancheuse = "trancheuse",
            orage = "orage",
            tourbillon = "tourbillon",
            tempete = "tempete",
            carmin = "carmin",
            meteore = "meteore",
            etoile = "etoile",
            irregulier = "irregulier",
            dissonance = "dissonance",
            eruption = "eruption",
            soleilCouchant = "soleil_couchant",
            indigo = "indigo",
            vague = "vague",
            deluge = "deluge",
            rafale = "rafale",
            typhon = "typhon",
            extirpeur = "extirpeur",
            croixDuSud = "croix_du_sud",
            lumineuse = "lumineuse",
            clairDeLune = "clair_de_lune",
            volDeNuit = "vol_de_nuit",
            foudre = "foudre",
            demoiselle = "demoiselle",
            ampoule = "ampoule";

    //Station of Awakening
    public static final String
            SoA_Menu1 = "soa.menu.1",
            SoA_Menu2 = "soa.menu.2",
            SoA_MenuOK = "soa.menu.ok",
            SoA_MenuCancel = "soa.menu.cancel",
            SoA_Warrior1 = "soa.warrior.1",
            SoA_Warrior2 = "soa.warrior.2",
            SoA_Warrior3 = "soa.warrior.3",
            SoA_Guardian1 = "soa.guardian.1",
            SoA_Guardian2 = "soa.guardian.2",
            SoA_Guardian3 = "soa.guardian.3",
            SoA_Mystic1 = "soa.mystic.1",
            SoA_Mystic2 = "soa.mystic.2",
            SoA_Mystic3 = "soa.mystic.3",
            SoA_ChoiceConfirm = "soa.choice.confirm",
            SoA_SacrificeConfirm = "soa.sacrifice.confirm",
            SoA_Ok = "soa.ok",
            SoA_Cancel = "soa.cancel",
            SoA_ConfirmCancel = "soa.confirm.cancel",
            SoA_Title = "soa.title",
            SoA_Subtitle = "soa.subtitle",
            SoA_ChoiceIntro1 = "soa.choice.intro.1",
            SoA_ChoiceIntro2 = "soa.choice.intro.2",
            SoA_ChoiceIntro3 = "soa.choice.intro.3",
            SoA_ChoiceIntro4 = "soa.choice.intro.4",
            SoA_SacrificeIntro1 = "soa.sacrifice.intro.1",
            SoA_SacrificeIntro2 = "soa.sacrifice.intro.2",
            SoA_ResetIntro1 = "soa.reset.intro.1",
            SoA_ResetIntro2 = "soa.reset.intro.2",
            SoA_Confirm1 = "soa.confirm.1",
            SoA_ConfirmWarrior = "soa.confirm.warrior",
            SoA_ConfirmGuardian = "soa.confirm.guardian",
            SoA_ConfirmMystic = "soa.confirm.mystic",
            SoA_Confirm3 = "soa.confirm.3",
            SoA_Confirm5 = "soa.confirm.5"
    ;
    
    public static String
    		HeartlessIntro1 = "heartless.intro.1", //This world has been connected
    		HeartlessIntro2 = "heartless.intro.2", //Tied to the darkness...
    		HeartlessIntro3 = "heartless.intro.3"; //Soon to be completely eclipsed

	public static String
			COIntro1 = "co.intro.1", //In this place, to find is to lose
			COIntro2 = "co.intro.2", //and to lose is to find.
			COIntro3 = "co.intro.3", //That is the way in Castle Oblivion
			COIntroTitle = "co.intro.title";

	//Map Cards
	public static String
			TranquilDarkness = "tranquil_darkness",
			TeemingDarkness = "teeming_darkness",
			FeebleDarkness = "feeble_darkness",
			AlmightyDarkness = "almighty_darkness",
			SleepingDarkness = "sleeping_darkness",
			LoomingDarkness = "looming_darkness",
			WhiteRoom = "white_room",
			BlackRoom = "black_room",
			BottomlessDarkness = "bottomless_darkness",
			RouletteRoom = "roulette_room",
			MartialWaking = "martial_waking",
			SorcerousWaking = "sorcerous_waking",
			AlchemicWaking = "alchemic_waking",
			StagnantSpace = "stagnant_space",
			CalmBounty = "calm_bounty",
			GuardedTrove = "guarded_trove",
			FalseBounty = "false_bounty",
			MomentsReprieve = "moments_reprieve",
			MinglingWorlds = "mingling_worlds",
			MoogleRoom = "moogle_room",
			ProsperousRepository = "prosperous_repository",
			TreacherousRepository = "treacherous_repository",
			ReposefulGrove = "reposeful_grove",
			WeightlessSpace = "weightless_space",
			UnknownRoom = "unknown_room",
			ConquerorsRespite = "conquerors_respite",
			EntranceHall = "entrance_hall",
			RoomOfBeginnings = "room_of_beginnings",
			RoomOfGuidance = "room_of_guidance",
			RoomOfTruth = "room_of_truth",
			RoomOfRewards = "room_of_rewards",

			RedCardPack = "red_card_pack",
			GreenCardPack = "green_card_pack",
			BlueCardPack = "blue_card_pack",
			RandomCardPack = "random_card_pack",
			RouletteBonus = "roulette_bonus";

	//World Cards
	public static String EmptyCard = "empty_card";

	public static String
			PlainsCard = "plains_card",
			TheNetherCard = "the_nether_card",
			TheEndCard = "the_end_card",
			CastleOblivionCard = "castle_oblivion_card",
			DesertCard = "desert_card",
			JungleCard = "jungle_card",
			OceanCard = "ocean_card",
			CaveCard = "cave_card",
			SnowyCard = "snowy_card",
			MushroomFieldsCard = "mushroom_fields_card",
			ForestCard = "forest_card",
			SwampCard = "swamp_card",
			BadlandsCard = "badlands_card";

	//Biome Memories
	public static String
			PlainsMemory = "plains_memory",
			TheNetherMemory = "the_nether_memory",
			TheEndMemory = "the_end_memory",
			CastleOblivionMemory = "castle_oblivion_memory",
			DesertMemory = "desert_memory",
			JungleMemory = "jungle_memory",
			OceanMemory = "ocean_memory",
			CaveMemory = "cave_memory",
			SnowyMemory = "snowy_memory",
			MushroomFieldsMemory = "mushroom_fields_memory",
			ForestMemory = "forest_memory",
			SwampMemory = "swamp_memory",
			BadlandsMemory = "badlands_memory";

	public static String
			WarningInformation = "warning.information",
			WarningAP = "warning.ap",
			WarningSell = "warning.sell",
			WarningPartyDisband = "warning.party.disband",
			WarningPartyLeave = "warning.party.leave",
			WarningPartyKick = "warning.party.kick",
			WarningShipOverwrite = "warning.ship.overwrite",
			WarningPlateOccupied = "warning.gummi.plate_occupied",
			WarningBannedBlocks = "warning.gummi.banned_blocks",
			WarningNoCore = "warning.gummi.no_core",
			WarningSingleCore = "warning.gummi.single_core",
			WarningShipTooBig = "warning.gummi.ship_too_big",
			WarningBlueprintTooBig = "warning.gummi.blueprint_too_big",
			WarningFileTooBig = "warning.gummi.file_too_big",
			WarningFileUnreadable = "warning.gummi.file_unreadable",
			WarningStruggleRange = "warning.struggle.out_of_range",
			WarningStockFull = "warning.stock.full";
}
