package online.kingdomkeys.kingdomkeys.item;

import java.util.function.Supplier;

import net.minecraft.inventory.EquipmentSlotType;
import net.minecraft.item.Food;
import net.minecraft.item.Item;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import online.kingdomkeys.kingdomkeys.KingdomKeys;
import online.kingdomkeys.kingdomkeys.client.sound.ModSounds;
import online.kingdomkeys.kingdomkeys.item.organization.ArrowgunsItem;
import online.kingdomkeys.kingdomkeys.item.organization.AxeSwordItem;
import online.kingdomkeys.kingdomkeys.item.organization.CardItem;
import online.kingdomkeys.kingdomkeys.item.organization.ChakramItem;
import online.kingdomkeys.kingdomkeys.item.organization.ClaymoreItem;
import online.kingdomkeys.kingdomkeys.item.organization.EtherealBladeItem;
import online.kingdomkeys.kingdomkeys.item.organization.KnifeItem;
import online.kingdomkeys.kingdomkeys.item.organization.LanceItem;
import online.kingdomkeys.kingdomkeys.item.organization.LexiconItem;
import online.kingdomkeys.kingdomkeys.item.organization.OrgShieldItem;
import online.kingdomkeys.kingdomkeys.item.organization.ScytheItem;
import online.kingdomkeys.kingdomkeys.item.organization.SitarItem;
import online.kingdomkeys.kingdomkeys.lib.Strings;
import online.kingdomkeys.kingdomkeys.synthesis.material.SynthesisItem;

public class ModItems {

	public static final DeferredRegister<Item> ITEMS = new DeferredRegister<>(ForgeRegistries.ITEMS, KingdomKeys.MODID);

    //Organization
  //  public static Item malice, sanction, overlord, veneration, autocracy, conquest, terminus, judgement, discipline, aristocracy, superiority, aggression, fury, despair, triumph, ruination, domination, annihilation, tyrant, magnificence, infinity, interdiction, roundFan, absolute, standalone, killerbee, stingray, counterweight, precision, dualHead, bahamut, gullwing, blueFrame, starShell, sunrise, ignition, armstrong, hardBoiledHeat, diabloEye, doubleTap, stardust, energyMuzzle, crimeAndPunishment, cupidsArrow, finalWeapon, sharpshooter, dryer, trumpet, zephyr, moonglade, aer, nescience, brume, asura, crux, paladin, fellking, nightcloud, shimmer, vortex, scission, heavenfall, aether, mazzaroth, hegemon, foxfire, yaksha, cynosura, dragonreign, lindworm, broom, wyvern, testerZero, productOne, deepFreeze, cryoliteShield, falseTheory, glacier, absoluteZero, gunz, mindel, snowslide, iceberg, inquisition, scrutiny, empiricism, edification, contrivance, wurm, subzero, coldBlood, diamondShield, aegis, frozenPride, potLid, snowman, reticence, goliath, copperRed, daybreak, colossus, ursaMajor, megacosm, terrene, fuligin, hardWinter, firefly, harbinger, redwood, sequoia, ironBlack, earthshine, octiron, hyperion, clarity, oneThousandAndOneNights, cardinalVirtue, skysplitter, bleepBloopBop, monolith, blackPrimer, whiteTome, illicitResearch, buriedSecrets, arcaneCompendium, dissentersNotes, nefariousCodex, mysticAlbum, cursedManual, tabooText, eldritchEsoterica, freakishBestiary, madmansVita, untitledWritings, abandonedDogma, atlasOfOmens, revoltingScrapbook, lostHeterodoxy, otherworldlyTales, indescribableLore, radicalTreatise, bookOfRetribution, midnightSnack, dearDiary, newMoon, werewolf, artemis, luminary, selene, moonrise, astrologia, crater, lunarPhase, crescent, gibbous, berserker, twilight, queenOfTheNight, balsamicMoon, orbit, lightYear, kingOfTheNight, moonset, horoscope, dichotomy, lunatic, justDesserts, bunnymoon, ashes, doldrums, delayedAction, diveBombers, combustion, moulinRouge, blazeOfGlory, prometheus, ifrit, magmaOcean, volcanics, inferno, sizzlingEdge, corona, ferrisWheel, burnout, omegaTrinity, outbreak, doubleEdge, wildfire, prominence, eternalFlames, pizzaCut, conformers, basicModel, tuneUp, quartet, quintet, overture, oldHand, daCapo, powerChord, fermata, interlude, serenade, songbird, riseToFame, rockStar, eightFinger, concerto, harmonics, millionBucks, fortissimo, upToEleven, sanctuary, arpeggio, princeOfAwesome, afterSchool, theFool, theMagician, theStar, theMoon, justice, theHierophant, theWorld, temperance, theHighPriestess, theTower, theHangedMan, death, theHermit, strength, theLovers, theChariot, theSun, theDevil, theEmpress, theEmperor, theJoker, fairGame, finestFantasy13, highRollersSecret, fickleErica, jiltedAnemone, proudAmaryllis, madSafflower, poorMelissa, tragicAllium, mournfulCineria, pseudoSilene, faithlessDigitalis, grimMuscari, docileVallota, quietBelladonna, partingIpheion, loftyGerbera, gallantAchillea, noblePeony, fearsomeAnise, vindictiveThistle, fairHelianthus, solemnMagnolia, hallowedLotus, gracefulDahlia, stirringLadle, daintyBellflowers, trancheuse, orage, tourbillon, tempete, carmin, meteore, etoile, irregulier, dissonance, eruption, soleilCouchant, indigo, vague, deluge, rafale, typhon, extirpeur, croixDuSud, lumineuse, clairDeLune, volDeNuit, foudre, demoiselle, ampoule;
    //Keyblades
    public static final RegistryObject<Item>
			abaddonPlasma = createKeybladeItem(Strings.abaddonPlasma),
			abyssalTide = createKeybladeItem(Strings.abyssalTide),
			acedsKeyblade = createKeybladeItem(Strings.acedsKeyblade),
			allForOne = createKeybladeItem(Strings.allForOne),
			astralBlast = createKeybladeItem(Strings.astralBlast),
			aubade = createKeybladeItem(Strings.aubade),
			avasKeyblade = createKeybladeItem(Strings.avasKeyblade),
			bondOfFlame = createKeybladeItem(Strings.bondOfFlame),
			brightcrest = createKeybladeItem(Strings.brightcrest),
			chaosRipper = createKeybladeItem(Strings.chaosRipper),
			circleOfLife = createKeybladeItem(Strings.circleOfLife),
			counterpoint = createKeybladeItem(Strings.counterpoint),
			crabclaw = createKeybladeItem(Strings.crabclaw),
			crownOfGuilt = createKeybladeItem(Strings.crownOfGuilt),
			darkerThanDark = createKeybladeItem(Strings.darkerThanDark),
			darkgnaw = createKeybladeItem(Strings.darkgnaw),
			decisivePumpkin = createKeybladeItem(Strings.decisivePumpkin),
			destinysEmbrace = createKeybladeItem(Strings.destinysEmbrace),
			diamondDust = createKeybladeItem(Strings.diamondDust),
			divewing = createKeybladeItem(Strings.divewing),
			divineRose = createKeybladeItem(Strings.divineRose),
			dualDisc = createKeybladeItem(Strings.dualDisc),
			earthshaker = createKeybladeItem(Strings.earthshaker),
			endOfPain = createKeybladeItem(Strings.endOfPain),
			endsOfTheEarth = createKeybladeItem(Strings.endsOfTheEarth),
			fairyHarp = createKeybladeItem(Strings.fairyHarp),
			fairyStars = createKeybladeItem(Strings.fairyStars),
			fatalCrest = createKeybladeItem(Strings.fatalCrest),
			fenrir = createKeybladeItem(Strings.fenrir),
			ferrisGear = createKeybladeItem(Strings.ferrisGear),
			flameLiberator = createKeybladeItem(Strings.flameLiberator),
			followtheWind = createKeybladeItem(Strings.followtheWind),
			frolicFlame = createKeybladeItem(Strings.frolicFlame),
			glimpseOfDarkness = createKeybladeItem(Strings.glimpseOfDarkness),
			guardianBell = createKeybladeItem(Strings.guardianBell),
			guardianSoul = createKeybladeItem(Strings.guardianSoul),
			gulasKeyblade = createKeybladeItem(Strings.gulasKeyblade),
			gullWing = createKeybladeItem(Strings.gullWing),
			herosCrest = createKeybladeItem(Strings.herosCrest),
			hiddenDragon = createKeybladeItem(Strings.hiddenDragon),
			hyperdrive = createKeybladeItem(Strings.hyperdrive),
			incompleteKiblade = createKeybladeItem(Strings.incompleteKiblade),
			invisKeyblade = createKeybladeItem(Strings.invisKeyblade),
			irasKeyblade = createKeybladeItem(Strings.irasKeyblade),
			jungleKing = createKeybladeItem(Strings.jungleKing),
			keybladeOfPeoplesHearts = createKeybladeItem(Strings.keybladeOfPeoplesHearts),
			kiblade = createKeybladeItem(Strings.kiblade),
			kingdomKey = createKeybladeItem(Strings.kingdomKey),
			kingdomKeyD = createKeybladeItem(Strings.kingdomKeyD),
			knockoutPunch = createKeybladeItem(Strings.knockoutPunch),
			ladyLuck = createKeybladeItem(Strings.ladyLuck),
			leviathan = createKeybladeItem(Strings.leviathan),
			lionheart = createKeybladeItem(Strings.lionheart),
			lostMemory = createKeybladeItem(Strings.lostMemory),
			lunarEclipse = createKeybladeItem(Strings.lunarEclipse),
			markOfAHero = createKeybladeItem(Strings.markOfAHero),
			mastersDefender = createKeybladeItem(Strings.mastersDefender),
			maverickFlare = createKeybladeItem(Strings.maverickFlare),
			metalChocobo = createKeybladeItem(Strings.metalChocobo),
			midnightRoar = createKeybladeItem(Strings.midnightRoar),
			mirageSplit = createKeybladeItem(Strings.mirageSplit),
			missingAche = createKeybladeItem(Strings.missingAche),
			monochrome = createKeybladeItem(Strings.monochrome),
			moogleOGlory = createKeybladeItem(Strings.moogleOGlory),
			mysteriousAbyss = createKeybladeItem(Strings.mysteriousAbyss),
			nightmaresEnd = createKeybladeItem(Strings.nightmaresEnd),
			nightmaresEndAndMirageSplit = createKeybladeItem(Strings.nightmaresEndAndMirageSplit),
			noName = createKeybladeItem(Strings.noName),
			noNameBBS = createKeybladeItem(Strings.noNameBBS),
			oathkeeper = createKeybladeItem(Strings.oathkeeper),
			oblivion = createKeybladeItem(Strings.oblivion),
			oceansRage = createKeybladeItem(Strings.oceansRage),
			olympia = createKeybladeItem(Strings.olympia),
			omegaWeapon = createKeybladeItem(Strings.omegaWeapon),
			ominousBlight = createKeybladeItem(Strings.ominousBlight),
			oneWingedAngel = createKeybladeItem(Strings.oneWingedAngel),
			painOfSolitude = createKeybladeItem(Strings.painOfSolitude),
			photonDebugger = createKeybladeItem(Strings.photonDebugger),
			pixiePetal = createKeybladeItem(Strings.pixiePetal),
			pumpkinhead = createKeybladeItem(Strings.pumpkinhead),
			rainfell = createKeybladeItem(Strings.rainfell),
			rejectionOfFate = createKeybladeItem(Strings.rejectionOfFate),
			royalRadiance = createKeybladeItem(Strings.royalRadiance),
			rumblingRose = createKeybladeItem(Strings.rumblingRose),
			shootingStar = createKeybladeItem(Strings.shootingStar),
			signOfInnocence = createKeybladeItem(Strings.signOfInnocence),
			silentDirge = createKeybladeItem(Strings.silentDirge),
			skullNoise = createKeybladeItem(Strings.skullNoise),
			sleepingLion = createKeybladeItem(Strings.sleepingLion),
			soulEater = createKeybladeItem(Strings.soulEater),
			spellbinder = createKeybladeItem(Strings.spellbinder),
			starSeeker = createKeybladeItem(Strings.starSeeker),
			starlight = createKeybladeItem(Strings.starlight),
			stormfall = createKeybladeItem(Strings.stormfall),
			strokeOfMidnight = createKeybladeItem(Strings.strokeOfMidnight),
			sweetDreams = createKeybladeItem(Strings.sweetDreams),
			sweetMemories = createKeybladeItem(Strings.sweetMemories),
			sweetstack = createKeybladeItem(Strings.sweetstack),
			threeWishes = createKeybladeItem(Strings.threeWishes),
			totalEclipse = createKeybladeItem(Strings.totalEclipse),
			treasureTrove = createKeybladeItem(Strings.treasureTrove),
			trueLightsFlight = createKeybladeItem(Strings.trueLightsFlight),
			twilightBlaze = createKeybladeItem(Strings.twilightBlaze),
			twoBecomeOne = createKeybladeItem(Strings.twoBecomeOne),
			ultimaWeaponBBS = createKeybladeItem(Strings.ultimaWeaponBBS),
			ultimaWeaponDDD = createKeybladeItem(Strings.ultimaWeaponDDD),
			ultimaWeaponKH1 = createKeybladeItem(Strings.ultimaWeaponKH1),
			ultimaWeaponKH2 = createKeybladeItem(Strings.ultimaWeaponKH2),
			ultimaWeaponKH3 = createKeybladeItem(Strings.ultimaWeaponKH3),
			umbrella = createKeybladeItem(Strings.umbrella),
			unbound = createKeybladeItem(Strings.unbound),
			victoryLine = createKeybladeItem(Strings.victoryLine),
			voidGear = createKeybladeItem(Strings.voidGear),
			waytotheDawn = createKeybladeItem(Strings.waytotheDawn),
			waywardWind = createKeybladeItem(Strings.waywardWind),
			winnersProof = createKeybladeItem(Strings.winnersProof),
			wishingLamp = createKeybladeItem(Strings.wishingLamp),
			wishingStar = createKeybladeItem(Strings.wishingStar),
			woodenKeyblade = createKeybladeItem(Strings.woodenKeyblade),
			woodenStick = createKeybladeItem(Strings.woodenStick),
			youngXehanortsKeyblade = createKeybladeItem(Strings.youngXehanortsKeyblade),
			zeroOne = createKeybladeItem(Strings.zeroOne),

			abaddonPlasmaChain = createNewItem(Strings.abaddonPlasmaChain, KeychainItem::new),
			abyssalTideChain = createNewItem(Strings.abyssalTideChain, KeychainItem::new),
			acedsKeybladeChain = createNewItem(Strings.acedsKeybladeChain, KeychainItem::new),
			allForOneChain = createNewItem(Strings.allForOneChain, KeychainItem::new),
			astralBlastChain = createNewItem(Strings.astralBlastChain, KeychainItem::new),
			aubadeChain = createNewItem(Strings.aubadeChain, KeychainItem::new),
			avasKeybladeChain = createNewItem(Strings.avasKeybladeChain, KeychainItem::new),
			bondOfFlameChain = createNewItem(Strings.bondOfFlameChain, KeychainItem::new),
			brightcrestChain = createNewItem(Strings.brightcrestChain, KeychainItem::new),
			chaosRipperChain = createNewItem(Strings.chaosRipperChain, KeychainItem::new),
			circleOfLifeChain = createNewItem(Strings.circleOfLifeChain, KeychainItem::new),
			counterpointChain = createNewItem(Strings.counterpointChain, KeychainItem::new),
			crabclawChain = createNewItem(Strings.crabclawChain, KeychainItem::new),
			crownOfGuiltChain = createNewItem(Strings.crownOfGuiltChain, KeychainItem::new),
			darkerThanDarkChain = createNewItem(Strings.darkerThanDarkChain, KeychainItem::new),
			darkgnawChain = createNewItem(Strings.darkgnawChain, KeychainItem::new),
			decisivePumpkinChain = createNewItem(Strings.decisivePumpkinChain, KeychainItem::new),
			destinysEmbraceChain = createNewItem(Strings.destinysEmbraceChain, KeychainItem::new),
			diamondDustChain = createNewItem(Strings.diamondDustChain, KeychainItem::new),
			divewingChain = createNewItem(Strings.divewingChain, KeychainItem::new),
			divineRoseChain = createNewItem(Strings.divineRoseChain, KeychainItem::new),
			dualDiscChain = createNewItem(Strings.dualDiscChain, KeychainItem::new),
			earthshakerChain = createNewItem(Strings.earthshakerChain, KeychainItem::new),
			endOfPainChain = createNewItem(Strings.endOfPainChain, KeychainItem::new),
			endsOfTheEarthChain = createNewItem(Strings.endsOfTheEarthChain, KeychainItem::new),
			fairyHarpChain = createNewItem(Strings.fairyHarpChain, KeychainItem::new),
			fairyStarsChain = createNewItem(Strings.fairyStarsChain, KeychainItem::new),
			fatalCrestChain = createNewItem(Strings.fatalCrestChain, KeychainItem::new),
			fenrirChain = createNewItem(Strings.fenrirChain, KeychainItem::new),
			ferrisGearChain = createNewItem(Strings.ferrisGearChain, KeychainItem::new),
			flameLiberatorChain = createNewItem(Strings.flameLiberatorChain, KeychainItem::new),
			followtheWindChain = createNewItem(Strings.followtheWindChain, KeychainItem::new),
			frolicFlameChain = createNewItem(Strings.frolicFlameChain, KeychainItem::new),
			glimpseOfDarknessChain = createNewItem(Strings.glimpseOfDarknessChain, KeychainItem::new),
			guardianBellChain = createNewItem(Strings.guardianBellChain, KeychainItem::new),
			guardianSoulChain = createNewItem(Strings.guardianSoulChain, KeychainItem::new),
			gulasKeybladeChain = createNewItem(Strings.gulasKeybladeChain, KeychainItem::new),
			gullWingChain = createNewItem(Strings.gullWingChain, KeychainItem::new),
			herosCrestChain = createNewItem(Strings.herosCrestChain, KeychainItem::new),
			hiddenDragonChain = createNewItem(Strings.hiddenDragonChain, KeychainItem::new),
			hyperdriveChain = createNewItem(Strings.hyperdriveChain, KeychainItem::new),
			incompleteKibladeChain = createNewItem(Strings.incompleteKibladeChain, KeychainItem::new),
			invisKeybladeChain = createNewItem(Strings.invisKeybladeChain, KeychainItem::new),
			irasKeybladeChain = createNewItem(Strings.irasKeybladeChain, KeychainItem::new),
			jungleKingChain = createNewItem(Strings.jungleKingChain, KeychainItem::new),
			keybladeOfPeoplesHeartsChain = createNewItem(Strings.keybladeOfPeoplesHeartsChain, KeychainItem::new),
			kibladeChain = createNewItem(Strings.kibladeChain, KeychainItem::new),
			kingdomKeyChain = createNewItem(Strings.kingdomKeyChain, KeychainItem::new),
			kingdomKeyDChain = createNewItem(Strings.kingdomKeyDChain, KeychainItem::new),
			knockoutPunchChain = createNewItem(Strings.knockoutPunchChain, KeychainItem::new),
			ladyLuckChain = createNewItem(Strings.ladyLuckChain, KeychainItem::new),
			leviathanChain = createNewItem(Strings.leviathanChain, KeychainItem::new),
			lionheartChain = createNewItem(Strings.lionheartChain, KeychainItem::new),
			lostMemoryChain = createNewItem(Strings.lostMemoryChain, KeychainItem::new),
			lunarEclipseChain = createNewItem(Strings.lunarEclipseChain, KeychainItem::new),
			markOfAHeroChain = createNewItem(Strings.markOfAHeroChain, KeychainItem::new),
			mastersDefenderChain = createNewItem(Strings.mastersDefenderChain, KeychainItem::new),
			maverickFlareChain = createNewItem(Strings.maverickFlareChain, KeychainItem::new),
			metalChocoboChain = createNewItem(Strings.metalChocoboChain, KeychainItem::new),
			midnightRoarChain = createNewItem(Strings.midnightRoarChain, KeychainItem::new),
			mirageSplitChain = createNewItem(Strings.mirageSplitChain, KeychainItem::new),
			missingAcheChain = createNewItem(Strings.missingAcheChain, KeychainItem::new),
			monochromeChain = createNewItem(Strings.monochromeChain, KeychainItem::new),
			moogleOGloryChain = createNewItem(Strings.moogleOGloryChain, KeychainItem::new),
			mysteriousAbyssChain = createNewItem(Strings.mysteriousAbyssChain, KeychainItem::new),
			nightmaresEndChain = createNewItem(Strings.nightmaresEndChain, KeychainItem::new),
			nightmaresEndAndMirageSplitChain = createNewItem(Strings.nightmaresEndAndMirageSplitChain, KeychainItem::new),
			noNameChain = createNewItem(Strings.noNameChain, KeychainItem::new),
			noNameBBSChain = createNewItem(Strings.noNameBBSChain, KeychainItem::new),
			oathkeeperChain = createNewItem(Strings.oathkeeperChain, KeychainItem::new),
			oblivionChain = createNewItem(Strings.oblivionChain, KeychainItem::new),
			oceansRageChain = createNewItem(Strings.oceansRageChain, KeychainItem::new),
			olympiaChain = createNewItem(Strings.olympiaChain, KeychainItem::new),
			omegaWeaponChain = createNewItem(Strings.omegaWeaponChain, KeychainItem::new),
			ominousBlightChain = createNewItem(Strings.ominousBlightChain, KeychainItem::new),
			oneWingedAngelChain = createNewItem(Strings.oneWingedAngelChain, KeychainItem::new),
			painOfSolitudeChain = createNewItem(Strings.painOfSolitudeChain, KeychainItem::new),
			photonDebuggerChain = createNewItem(Strings.photonDebuggerChain, KeychainItem::new),
			pixiePetalChain = createNewItem(Strings.pixiePetalChain, KeychainItem::new),
			pumpkinheadChain = createNewItem(Strings.pumpkinheadChain, KeychainItem::new),
			rainfellChain = createNewItem(Strings.rainfellChain, KeychainItem::new),
			rejectionOfFateChain = createNewItem(Strings.rejectionOfFateChain, KeychainItem::new),
			royalRadianceChain = createNewItem(Strings.royalRadianceChain, KeychainItem::new),
			rumblingRoseChain = createNewItem(Strings.rumblingRoseChain, KeychainItem::new),
			shootingStarChain = createNewItem(Strings.shootingStarChain, KeychainItem::new),
			signOfInnocenceChain = createNewItem(Strings.signOfInnocenceChain, KeychainItem::new),
			silentDirgeChain = createNewItem(Strings.silentDirgeChain, KeychainItem::new),
			skullNoiseChain = createNewItem(Strings.skullNoiseChain, KeychainItem::new),
			sleepingLionChain = createNewItem(Strings.sleepingLionChain, KeychainItem::new),
			soulEaterChain = createNewItem(Strings.soulEaterChain, KeychainItem::new),
			spellbinderChain = createNewItem(Strings.spellbinderChain, KeychainItem::new),
			starSeekerChain = createNewItem(Strings.starSeekerChain, KeychainItem::new),
			starlightChain = createNewItem(Strings.starlightChain, KeychainItem::new),
			stormfallChain = createNewItem(Strings.stormfallChain, KeychainItem::new),
			strokeOfMidnightChain = createNewItem(Strings.strokeOfMidnightChain, KeychainItem::new),
			sweetDreamsChain = createNewItem(Strings.sweetDreamsChain, KeychainItem::new),
			sweetMemoriesChain = createNewItem(Strings.sweetMemoriesChain, KeychainItem::new),
			sweetstackChain = createNewItem(Strings.sweetstackChain, KeychainItem::new),
			threeWishesChain = createNewItem(Strings.threeWishesChain, KeychainItem::new),
			totalEclipseChain = createNewItem(Strings.totalEclipseChain, KeychainItem::new),
			treasureTroveChain = createNewItem(Strings.treasureTroveChain, KeychainItem::new),
			trueLightsFlightChain = createNewItem(Strings.trueLightsFlightChain, KeychainItem::new),
			twilightBlazeChain = createNewItem(Strings.twilightBlazeChain, KeychainItem::new),
			twoBecomeOneChain = createNewItem(Strings.twoBecomeOneChain, KeychainItem::new),
			ultimaWeaponBBSChain = createNewItem(Strings.ultimaWeaponBBSChain, KeychainItem::new),
			ultimaWeaponDDDChain = createNewItem(Strings.ultimaWeaponDDDChain, KeychainItem::new),
			ultimaWeaponKH1Chain = createNewItem(Strings.ultimaWeaponKH1Chain, KeychainItem::new),
			ultimaWeaponKH2Chain = createNewItem(Strings.ultimaWeaponKH2Chain, KeychainItem::new),
			ultimaWeaponKH3Chain = createNewItem(Strings.ultimaWeaponKH3Chain, KeychainItem::new),
			umbrellaChain = createNewItem(Strings.umbrellaChain, KeychainItem::new),
			unboundChain = createNewItem(Strings.unboundChain, KeychainItem::new),
			victoryLineChain = createNewItem(Strings.victoryLineChain, KeychainItem::new),
			voidGearChain = createNewItem(Strings.voidGearChain, KeychainItem::new),
			waytotheDawnChain = createNewItem(Strings.waytotheDawnChain, KeychainItem::new),
			waywardWindChain = createNewItem(Strings.waywardWindChain, KeychainItem::new),
			winnersProofChain = createNewItem(Strings.winnersProofChain, KeychainItem::new),
			wishingLampChain = createNewItem(Strings.wishingLampChain, KeychainItem::new),
			wishingStarChain = createNewItem(Strings.wishingStarChain, KeychainItem::new),
			youngXehanortsKeybladeChain = createNewItem(Strings.youngXehanortsKeybladeChain, KeychainItem::new),
			zeroOneChain = createNewItem(Strings.zeroOneChain, KeychainItem::new),
			
			malice = createNewItem(Strings.malice, EtherealBladeItem::new),
			sanction = createNewItem(Strings.sanction, EtherealBladeItem::new),
			overlord = createNewItem(Strings.overlord, EtherealBladeItem::new),
			veneration = createNewItem(Strings.veneration, EtherealBladeItem::new),
			autocracy = createNewItem(Strings.autocracy, EtherealBladeItem::new),
			conquest = createNewItem(Strings.conquest, EtherealBladeItem::new),
			terminus = createNewItem(Strings.terminus, EtherealBladeItem::new),
			judgement = createNewItem(Strings.judgement, EtherealBladeItem::new),
			discipline = createNewItem(Strings.discipline, EtherealBladeItem::new),
			aristocracy = createNewItem(Strings.aristocracy, EtherealBladeItem::new),
			superiority = createNewItem(Strings.superiority, EtherealBladeItem::new),
			aggression = createNewItem(Strings.aggression, EtherealBladeItem::new),
			fury = createNewItem(Strings.fury, EtherealBladeItem::new),
			despair = createNewItem(Strings.despair, EtherealBladeItem::new),
			triumph = createNewItem(Strings.triumph, EtherealBladeItem::new),
			ruination = createNewItem(Strings.ruination, EtherealBladeItem::new),
			domination = createNewItem(Strings.domination, EtherealBladeItem::new),
			annihilation = createNewItem(Strings.annihilation, EtherealBladeItem::new),
			tyrant = createNewItem(Strings.tyrant, EtherealBladeItem::new),
			magnificence = createNewItem(Strings.magnificence, EtherealBladeItem::new),
			infinity = createNewItem(Strings.infinity, EtherealBladeItem::new),
			interdiction = createNewItem(Strings.interdiction, EtherealBladeItem::new),
			roundFan = createNewItem(Strings.roundFan, EtherealBladeItem::new),
			absolute = createNewItem(Strings.absolute, EtherealBladeItem::new),
			
			standalone = createNewItem(Strings.standalone, ArrowgunsItem::new),
			killerbee = createNewItem(Strings.killerbee, ArrowgunsItem::new),
			stingray = createNewItem(Strings.stingray, ArrowgunsItem::new),
			counterweight = createNewItem(Strings.counterweight, ArrowgunsItem::new),
			precision = createNewItem(Strings.precision, ArrowgunsItem::new),
			dualHead = createNewItem(Strings.dualHead, ArrowgunsItem::new),
			bahamut = createNewItem(Strings.bahamut, ArrowgunsItem::new),
			gullwing = createNewItem(Strings.gullwing, ArrowgunsItem::new),
			blueFrame = createNewItem(Strings.blueFrame, ArrowgunsItem::new),
			starShell = createNewItem(Strings.starShell, ArrowgunsItem::new),
			sunrise = createNewItem(Strings.sunrise, ArrowgunsItem::new),
			ignition = createNewItem(Strings.ignition, ArrowgunsItem::new),
			armstrong = createNewItem(Strings.armstrong, ArrowgunsItem::new),
			hardBoiledHeat = createNewItem(Strings.hardBoiledHeat, ArrowgunsItem::new),
			diabloEye = createNewItem(Strings.diabloEye, ArrowgunsItem::new),
			doubleTap = createNewItem(Strings.doubleTap, ArrowgunsItem::new),
			stardust = createNewItem(Strings.stardust, ArrowgunsItem::new),
			energyMuzzle = createNewItem(Strings.energyMuzzle, ArrowgunsItem::new),
			crimeAndPunishment = createNewItem(Strings.crimeAndPunishment, ArrowgunsItem::new),
			cupidsArrow = createNewItem(Strings.cupidsArrow, ArrowgunsItem::new),
			finalWeapon = createNewItem(Strings.finalWeapon, ArrowgunsItem::new),
			sharpshooter = createNewItem(Strings.sharpshooter, ArrowgunsItem::new),
			dryer = createNewItem(Strings.dryer, ArrowgunsItem::new),
			trumpet = createNewItem(Strings.trumpet, ArrowgunsItem::new),
			
			zephyr = createNewItem(Strings.zephyr, LanceItem::new),
			moonglade = createNewItem(Strings.moonglade, LanceItem::new),
			aer = createNewItem(Strings.aer, LanceItem::new),
			nescience = createNewItem(Strings.nescience, LanceItem::new),
			brume = createNewItem(Strings.brume, LanceItem::new),
			asura = createNewItem(Strings.asura, LanceItem::new),
			crux = createNewItem(Strings.crux, LanceItem::new),
			paladin = createNewItem(Strings.paladin, LanceItem::new),
			fellking = createNewItem(Strings.fellking, LanceItem::new),
			nightcloud = createNewItem(Strings.nightcloud, LanceItem::new),
			shimmer = createNewItem(Strings.shimmer, LanceItem::new),
			vortex = createNewItem(Strings.vortex, LanceItem::new),
			scission = createNewItem(Strings.scission, LanceItem::new),
			heavenfall = createNewItem(Strings.heavenfall, LanceItem::new),
			aether = createNewItem(Strings.aether, LanceItem::new),
			mazzaroth = createNewItem(Strings.mazzaroth, LanceItem::new),
			hegemon = createNewItem(Strings.hegemon, LanceItem::new),
			foxfire = createNewItem(Strings.foxfire, LanceItem::new),
			yaksha = createNewItem(Strings.yaksha, LanceItem::new),
			cynosura = createNewItem(Strings.cynosura, LanceItem::new),
			dragonreign = createNewItem(Strings.dragonreign, LanceItem::new),
			lindworm = createNewItem(Strings.lindworm, LanceItem::new),
			broom = createNewItem(Strings.broom, LanceItem::new),
			wyvern = createNewItem(Strings.wyvern, LanceItem::new),
			
			testerZero = createNewItem(Strings.testerZero, OrgShieldItem::new),
			productOne = createNewItem(Strings.productOne, OrgShieldItem::new),
			deepFreeze = createNewItem(Strings.deepFreeze, OrgShieldItem::new),
			cryoliteShield = createNewItem(Strings.cryoliteShield, OrgShieldItem::new),
			falseTheory = createNewItem(Strings.falseTheory, OrgShieldItem::new),
			glacier = createNewItem(Strings.glacier, OrgShieldItem::new),
			absoluteZero = createNewItem(Strings.absoluteZero, OrgShieldItem::new),
			gunz = createNewItem(Strings.gunz, OrgShieldItem::new),
			mindel = createNewItem(Strings.mindel, OrgShieldItem::new),
			snowslide = createNewItem(Strings.snowslide, OrgShieldItem::new),
			iceberg = createNewItem(Strings.iceberg, OrgShieldItem::new),
			inquisition = createNewItem(Strings.inquisition, OrgShieldItem::new),
			scrutiny = createNewItem(Strings.scrutiny, OrgShieldItem::new),
			empiricism = createNewItem(Strings.empiricism, OrgShieldItem::new),
			edification = createNewItem(Strings.edification, OrgShieldItem::new),
			contrivance = createNewItem(Strings.contrivance, OrgShieldItem::new),
			wurm = createNewItem(Strings.wurm, OrgShieldItem::new),
			subzero = createNewItem(Strings.subzero, OrgShieldItem::new),
			coldBlood = createNewItem(Strings.coldBlood, OrgShieldItem::new),
			diamondShield = createNewItem(Strings.diamondShield, OrgShieldItem::new),
			aegis = createNewItem(Strings.aegis, OrgShieldItem::new),
			frozenPride = createNewItem(Strings.frozenPride, OrgShieldItem::new),
			potLid = createNewItem(Strings.potLid, OrgShieldItem::new),
			snowman = createNewItem(Strings.snowman, OrgShieldItem::new),
			
			reticence = createNewItem(Strings.reticence, AxeSwordItem::new),
			goliath = createNewItem(Strings.goliath, AxeSwordItem::new),
			copperRed = createNewItem(Strings.copperRed, AxeSwordItem::new),
			daybreak = createNewItem(Strings.daybreak, AxeSwordItem::new),
			colossus = createNewItem(Strings.colossus, AxeSwordItem::new),
			ursaMajor = createNewItem(Strings.ursaMajor, AxeSwordItem::new),
			megacosm = createNewItem(Strings.megacosm, AxeSwordItem::new),
			terrene = createNewItem(Strings.terrene, AxeSwordItem::new),
			fuligin = createNewItem(Strings.fuligin, AxeSwordItem::new),
			hardWinter = createNewItem(Strings.hardWinter, AxeSwordItem::new),
			firefly = createNewItem(Strings.firefly, AxeSwordItem::new),
			harbinger = createNewItem(Strings.harbinger, AxeSwordItem::new),
			redwood = createNewItem(Strings.redwood, AxeSwordItem::new),
			sequoia = createNewItem(Strings.sequoia, AxeSwordItem::new),
			ironBlack = createNewItem(Strings.ironBlack, AxeSwordItem::new),
			earthshine = createNewItem(Strings.earthshine, AxeSwordItem::new),
			octiron = createNewItem(Strings.octiron, AxeSwordItem::new),
			hyperion = createNewItem(Strings.hyperion, AxeSwordItem::new),
			clarity = createNewItem(Strings.clarity, AxeSwordItem::new),
			oneThousandAndOneNights = createNewItem(Strings.oneThousandAndOneNights, AxeSwordItem::new),
			cardinalVirtue = createNewItem(Strings.cardinalVirtue, AxeSwordItem::new),
			skysplitter = createNewItem(Strings.skysplitter, AxeSwordItem::new),
			bleepBloopBop = createNewItem(Strings.bleepBloopBop, AxeSwordItem::new),
			monolith = createNewItem(Strings.monolith, AxeSwordItem::new),
			
			blackPrimer = createNewItem(Strings.blackPrimer, LexiconItem::new),
			whiteTome = createNewItem(Strings.whiteTome, LexiconItem::new),
			illicitResearch = createNewItem(Strings.illicitResearch, LexiconItem::new),
			buriedSecrets = createNewItem(Strings.buriedSecrets, LexiconItem::new),
			arcaneCompendium = createNewItem(Strings.arcaneCompendium, LexiconItem::new),
			dissentersNotes = createNewItem(Strings.dissentersNotes, LexiconItem::new),
			nefariousCodex = createNewItem(Strings.nefariousCodex, LexiconItem::new),
			mysticAlbum = createNewItem(Strings.mysticAlbum, LexiconItem::new),
			cursedManual = createNewItem(Strings.cursedManual, LexiconItem::new),
			tabooText = createNewItem(Strings.tabooText, LexiconItem::new),
			eldritchEsoterica = createNewItem(Strings.eldritchEsoterica, LexiconItem::new),
			freakishBestiary = createNewItem(Strings.freakishBestiary, LexiconItem::new),
			madmansVita = createNewItem(Strings.madmansVita, LexiconItem::new),
			untitledWritings = createNewItem(Strings.untitledWritings, LexiconItem::new),
			abandonedDogma = createNewItem(Strings.abandonedDogma, LexiconItem::new),
			atlasOfOmens = createNewItem(Strings.atlasOfOmens, LexiconItem::new),
			revoltingScrapbook = createNewItem(Strings.revoltingScrapbook, LexiconItem::new),
			lostHeterodoxy = createNewItem(Strings.lostHeterodoxy, LexiconItem::new),
			otherworldlyTales = createNewItem(Strings.otherworldlyTales, LexiconItem::new),
			indescribableLore = createNewItem(Strings.indescribableLore, LexiconItem::new),
			radicalTreatise = createNewItem(Strings.radicalTreatise, LexiconItem::new),
			bookOfRetribution = createNewItem(Strings.bookOfRetribution, LexiconItem::new),
			midnightSnack = createNewItem(Strings.midnightSnack, LexiconItem::new),
			dearDiary = createNewItem(Strings.dearDiary, LexiconItem::new),
			
			newMoon = createNewItem(Strings.newMoon, ClaymoreItem::new),
			werewolf = createNewItem(Strings.werewolf, ClaymoreItem::new),
			artemis = createNewItem(Strings.artemis, ClaymoreItem::new),
			luminary = createNewItem(Strings.luminary, ClaymoreItem::new),
			selene = createNewItem(Strings.selene, ClaymoreItem::new),
			moonrise = createNewItem(Strings.moonrise, ClaymoreItem::new),
			astrologia = createNewItem(Strings.astrologia, ClaymoreItem::new),
			crater = createNewItem(Strings.crater, ClaymoreItem::new),
			lunarPhase = createNewItem(Strings.lunarPhase, ClaymoreItem::new),
			crescent = createNewItem(Strings.crescent, ClaymoreItem::new),
			gibbous = createNewItem(Strings.gibbous, ClaymoreItem::new),
			berserker = createNewItem(Strings.berserker, ClaymoreItem::new),
			twilight = createNewItem(Strings.twilight, ClaymoreItem::new),
			queenOfTheNight = createNewItem(Strings.queenOfTheNight, ClaymoreItem::new),
			balsamicMoon = createNewItem(Strings.balsamicMoon, ClaymoreItem::new),
			orbit = createNewItem(Strings.orbit, ClaymoreItem::new),
			lightYear = createNewItem(Strings.lightYear, ClaymoreItem::new),
			kingOfTheNight = createNewItem(Strings.kingOfTheNight, ClaymoreItem::new),
			moonset = createNewItem(Strings.moonset, ClaymoreItem::new),
			horoscope = createNewItem(Strings.horoscope, ClaymoreItem::new),
			dichotomy = createNewItem(Strings.dichotomy, ClaymoreItem::new),
			lunatic = createNewItem(Strings.lunatic, ClaymoreItem::new),
			justDesserts = createNewItem(Strings.justDesserts, ClaymoreItem::new),
			bunnymoon = createNewItem(Strings.bunnymoon, ClaymoreItem::new),
			
			ashes = createNewItem(Strings.ashes, ChakramItem::new),
			doldrums = createNewItem(Strings.doldrums, ChakramItem::new),
			delayedAction = createNewItem(Strings.delayedAction, ChakramItem::new),
			diveBombers = createNewItem(Strings.diveBombers, ChakramItem::new),
			combustion = createNewItem(Strings.combustion, ChakramItem::new),
			moulinRouge = createNewItem(Strings.moulinRouge, ChakramItem::new),
			blazeOfGlory = createNewItem(Strings.blazeOfGlory, ChakramItem::new),
			prometheus = createNewItem(Strings.prometheus, ChakramItem::new),
			ifrit = createNewItem(Strings.ifrit, ChakramItem::new),
			magmaOcean = createNewItem(Strings.magmaOcean, ChakramItem::new),
			volcanics = createNewItem(Strings.volcanics, ChakramItem::new),
			inferno = createNewItem(Strings.inferno, ChakramItem::new),
			sizzlingEdge = createNewItem(Strings.sizzlingEdge, ChakramItem::new),
			corona = createNewItem(Strings.corona, ChakramItem::new),
			ferrisWheel = createNewItem(Strings.ferrisWheel, ChakramItem::new),
			burnout = createNewItem(Strings.burnout, ChakramItem::new),
			omegaTrinity = createNewItem(Strings.omegaTrinity, ChakramItem::new),
			outbreak = createNewItem(Strings.outbreak, ChakramItem::new),
			doubleEdge = createNewItem(Strings.doubleEdge, ChakramItem::new),
			wildfire = createNewItem(Strings.wildfire, ChakramItem::new),
			prominence = createNewItem(Strings.prominence, ChakramItem::new),
			eternalFlames = createNewItem(Strings.eternalFlames, ChakramItem::new),
			pizzaCut = createNewItem(Strings.pizzaCut, ChakramItem::new),
			conformers = createNewItem(Strings.conformers, ChakramItem::new),
			
			basicModel = createNewItem(Strings.basicModel, SitarItem::new),
			tuneUp = createNewItem(Strings.tuneUp, SitarItem::new),
			quartet = createNewItem(Strings.quartet, SitarItem::new),
			quintet = createNewItem(Strings.quintet, SitarItem::new),
			overture = createNewItem(Strings.overture, SitarItem::new),
			oldHand = createNewItem(Strings.oldHand, SitarItem::new),
			daCapo = createNewItem(Strings.daCapo, SitarItem::new),
			powerChord = createNewItem(Strings.powerChord, SitarItem::new),
			fermata = createNewItem(Strings.fermata, SitarItem::new),
			interlude = createNewItem(Strings.interlude, SitarItem::new),
			serenade = createNewItem(Strings.serenade, SitarItem::new),
			songbird = createNewItem(Strings.songbird, SitarItem::new),
			riseToFame = createNewItem(Strings.riseToFame, SitarItem::new),
			rockStar = createNewItem(Strings.rockStar, SitarItem::new),
			eightFinger = createNewItem(Strings.eightFinger, SitarItem::new),
			concerto = createNewItem(Strings.concerto, SitarItem::new),
			harmonics = createNewItem(Strings.harmonics, SitarItem::new),
			millionBucks = createNewItem(Strings.millionBucks, SitarItem::new),
			fortissimo = createNewItem(Strings.fortissimo, SitarItem::new),
			upToEleven = createNewItem(Strings.upToEleven, SitarItem::new),
			sanctuary = createNewItem(Strings.sanctuary, SitarItem::new),
			arpeggio = createNewItem(Strings.arpeggio, SitarItem::new),
			princeOfAwesome = createNewItem(Strings.princeOfAwesome, SitarItem::new),
			afterSchool = createNewItem(Strings.afterSchool, SitarItem::new),
			
			theFool = createNewItem(Strings.theFool, CardItem::new),
			theMagician = createNewItem(Strings.theMagician, CardItem::new),
			theStar = createNewItem(Strings.theStar, CardItem::new),
			theMoon = createNewItem(Strings.theMoon, CardItem::new),
			justice = createNewItem(Strings.justice, CardItem::new),
			theHierophant = createNewItem(Strings.theHierophant, CardItem::new),
			theWorld = createNewItem(Strings.theWorld, CardItem::new),
			temperance = createNewItem(Strings.temperance, CardItem::new),
			theHighPriestess = createNewItem(Strings.theHighPriestess, CardItem::new),
			theTower = createNewItem(Strings.theTower, CardItem::new),
			theHangedMan = createNewItem(Strings.theHangedMan, CardItem::new),
			death = createNewItem(Strings.death, CardItem::new),
			theHermit = createNewItem(Strings.theHermit, CardItem::new),
			strength = createNewItem(Strings.strength, CardItem::new),
			theLovers = createNewItem(Strings.theLovers, CardItem::new),
			theChariot = createNewItem(Strings.theChariot, CardItem::new),
			theSun = createNewItem(Strings.theSun, CardItem::new),
			theDevil = createNewItem(Strings.theDevil, CardItem::new),
			theEmpress = createNewItem(Strings.theEmpress, CardItem::new),
			theEmperor = createNewItem(Strings.theEmperor, CardItem::new),
			theJoker = createNewItem(Strings.theJoker, CardItem::new),
			fairGame = createNewItem(Strings.fairGame, CardItem::new),
			finestFantasy13 = createNewItem(Strings.finestFantasy13, CardItem::new),
			highRollersSecret = createNewItem(Strings.highRollersSecret, CardItem::new),
			
			fickleErica = createNewItem(Strings.fickleErica, ScytheItem::new),
			jiltedAnemone = createNewItem(Strings.jiltedAnemone, ScytheItem::new),
			proudAmaryllis = createNewItem(Strings.proudAmaryllis, ScytheItem::new),
			madSafflower = createNewItem(Strings.madSafflower, ScytheItem::new),
			poorMelissa = createNewItem(Strings.poorMelissa, ScytheItem::new),
			tragicAllium = createNewItem(Strings.tragicAllium, ScytheItem::new),
			mournfulCineria = createNewItem(Strings.mournfulCineria, ScytheItem::new),
			pseudoSilene = createNewItem(Strings.pseudoSilene, ScytheItem::new),
			faithlessDigitalis = createNewItem(Strings.faithlessDigitalis, ScytheItem::new),
			grimMuscari = createNewItem(Strings.grimMuscari, ScytheItem::new),
			docileVallota = createNewItem(Strings.docileVallota, ScytheItem::new),
			quietBelladonna = createNewItem(Strings.quietBelladonna, ScytheItem::new),
			partingIpheion = createNewItem(Strings.partingIpheion, ScytheItem::new),
			loftyGerbera = createNewItem(Strings.loftyGerbera, ScytheItem::new),
			gallantAchillea = createNewItem(Strings.gallantAchillea, ScytheItem::new),
			noblePeony = createNewItem(Strings.noblePeony, ScytheItem::new),
			fearsomeAnise = createNewItem(Strings.fearsomeAnise, ScytheItem::new),
			vindictiveThistle = createNewItem(Strings.vindictiveThistle, ScytheItem::new),
			fairHelianthus = createNewItem(Strings.fairHelianthus, ScytheItem::new),
			solemnMagnolia = createNewItem(Strings.solemnMagnolia, ScytheItem::new),
			hallowedLotus = createNewItem(Strings.hallowedLotus, ScytheItem::new),
			gracefulDahlia = createNewItem(Strings.gracefulDahlia, ScytheItem::new),
			stirringLadle = createNewItem(Strings.stirringLadle, ScytheItem::new),
			daintyBellflowers = createNewItem(Strings.daintyBellflowers, ScytheItem::new),
			
			trancheuse = createNewItem(Strings.trancheuse, KnifeItem::new),
			orage = createNewItem(Strings.orage, KnifeItem::new),
			tourbillon = createNewItem(Strings.tourbillon, KnifeItem::new),
			tempete = createNewItem(Strings.tempete, KnifeItem::new),
			carmin = createNewItem(Strings.carmin, KnifeItem::new),
			meteore = createNewItem(Strings.meteore, KnifeItem::new),
			etoile = createNewItem(Strings.etoile, KnifeItem::new),
			irregulier = createNewItem(Strings.irregulier, KnifeItem::new),
			dissonance = createNewItem(Strings.dissonance, KnifeItem::new),
			eruption = createNewItem(Strings.eruption, KnifeItem::new),
			soleilCouchant = createNewItem(Strings.soleilCouchant, KnifeItem::new),
			indigo = createNewItem(Strings.indigo, KnifeItem::new),
			vague = createNewItem(Strings.vague, KnifeItem::new),
			deluge = createNewItem(Strings.deluge, KnifeItem::new),
			rafale = createNewItem(Strings.rafale, KnifeItem::new),
			typhon = createNewItem(Strings.typhon, KnifeItem::new),
			extirpeur = createNewItem(Strings.extirpeur, KnifeItem::new),
			croixDuSud = createNewItem(Strings.croixDuSud, KnifeItem::new),
			lumineuse = createNewItem(Strings.lumineuse, KnifeItem::new),
			clairDeLune = createNewItem(Strings.clairDeLune, KnifeItem::new),
			volDeNuit = createNewItem(Strings.volDeNuit, KnifeItem::new),
			foudre = createNewItem(Strings.foudre, KnifeItem::new),
			demoiselle = createNewItem(Strings.demoiselle, KnifeItem::new),
			ampoule = createNewItem(Strings.ampoule, KnifeItem::new),


			organizationRobe_Helmet = createArmorItem(Strings.organizationHood, KKArmorMaterial.ORGANIZATION, EquipmentSlotType.HEAD),
			organizationRobe_Chestplate = createArmorItem(Strings.organizationChestplate, KKArmorMaterial.ORGANIZATION, EquipmentSlotType.CHEST),
			organizationRobe_Leggings = createArmorItem(Strings.organizationLeggings, KKArmorMaterial.ORGANIZATION, EquipmentSlotType.LEGS),
			organizationRobe_Boots = createArmorItem(Strings.organizationBoots, KKArmorMaterial.ORGANIZATION, EquipmentSlotType.FEET),

			terra_Helmet = createArmorItem(Strings.terraHelmet,KKArmorMaterial.TERRA, EquipmentSlotType.HEAD),
			terra_Chestplate = createArmorItem(Strings.terraChestplate, KKArmorMaterial.TERRA, EquipmentSlotType.CHEST),
			terra_Leggings = createArmorItem(Strings.terraLeggings, KKArmorMaterial.TERRA, EquipmentSlotType.LEGS),
			terra_Boots = createArmorItem(Strings.terraBoots, KKArmorMaterial.TERRA,EquipmentSlotType.FEET),

			ventus_Helmet = createArmorItem(Strings.ventusHelmet, KKArmorMaterial.VENTUS, EquipmentSlotType.HEAD, "ventus"),
			ventus_Chestplate = createArmorItem(Strings.ventusChestplate, KKArmorMaterial.VENTUS, EquipmentSlotType.CHEST, "ventus"),
			ventus_Leggings = createArmorItem(Strings.ventusLeggings, KKArmorMaterial.VENTUS, EquipmentSlotType.LEGS, "ventus"),
			ventus_Boots = createArmorItem(Strings.ventusBoots, KKArmorMaterial.VENTUS, EquipmentSlotType.FEET, "ventus"),

			aqua_Helmet = createArmorItem(Strings.aquaHelmet, KKArmorMaterial.AQUA, EquipmentSlotType.HEAD),
			aqua_Chestplate = createArmorItem(Strings.aquaChestplate, KKArmorMaterial.AQUA, EquipmentSlotType.CHEST),
			aqua_Leggings = createArmorItem(Strings.aquaLeggings, KKArmorMaterial.AQUA, EquipmentSlotType.LEGS),
			aqua_Boots = createArmorItem(Strings.aquaBoots, KKArmorMaterial.AQUA, EquipmentSlotType.FEET),

			eraqus_Helmet = createArmorItem(Strings.eraqusHelmet, KKArmorMaterial.ERAQUS, EquipmentSlotType.HEAD),
			eraqus_Chestplate = createArmorItem(Strings.eraqusChestplate, KKArmorMaterial.ERAQUS, EquipmentSlotType.CHEST),
			eraqus_Leggings = createArmorItem(Strings.eraqusLeggings, KKArmorMaterial.ERAQUS, EquipmentSlotType.LEGS),
			eraqus_Boots = createArmorItem(Strings.eraqusBoots, KKArmorMaterial.ERAQUS, EquipmentSlotType.FEET),

			vanitas_Helmet = createArmorItem(Strings.vanitasHelmet, KKArmorMaterial.VANITAS, EquipmentSlotType.HEAD),
			vanitas_Chestplate = createArmorItem(Strings.vanitasChestplate, KKArmorMaterial.VANITAS, EquipmentSlotType.CHEST),
			vanitas_Leggings = createArmorItem(Strings.vanitasLeggings, KKArmorMaterial.VANITAS, EquipmentSlotType.LEGS),
			vanitas_Boots = createArmorItem(Strings.vanitasBoots, KKArmorMaterial.VANITAS, EquipmentSlotType.FEET),

			nightmareVentus_Helmet = createArmorItem(Strings.nightmareVentusHelmet, KKArmorMaterial.NIGHTMAREVEN, EquipmentSlotType.HEAD),
			nightmareVentus_Chestplate = createArmorItem(Strings.nightmareVentusChestplate, KKArmorMaterial.NIGHTMAREVEN, EquipmentSlotType.CHEST),
			nightmareVentus_Leggings = createArmorItem(Strings.nightmareVentusLeggings, KKArmorMaterial.NIGHTMAREVEN, EquipmentSlotType.LEGS),
			nightmareVentus_Boots = createArmorItem(Strings.nightmareVentusBoots, KKArmorMaterial.NIGHTMAREVEN, EquipmentSlotType.FEET),

			antiCoat_Helmet = createArmorItem(Strings.antiCoatHelmet, KKArmorMaterial.ANTICOAT, EquipmentSlotType.HEAD),
			antiCoat_Chestplate = createArmorItem(Strings.antiCoatChestplate, KKArmorMaterial.ANTICOAT, EquipmentSlotType.CHEST),
			antiCoat_Leggings = createArmorItem(Strings.antiCoatLeggings, KKArmorMaterial.ANTICOAT, EquipmentSlotType.LEGS),
			antiCoat_Boots = createArmorItem(Strings.antiCoatBoots, KKArmorMaterial.ANTICOAT, EquipmentSlotType.FEET),

			xemnas_Helmet = createArmorItem(Strings.xemnasHelmet, KKArmorMaterial.XEMNAS, EquipmentSlotType.HEAD),
			xemnas_Chestplate = createArmorItem(Strings.xemnasChestplate, KKArmorMaterial.XEMNAS, EquipmentSlotType.CHEST),
			xemnas_Leggings = createArmorItem(Strings.xemnasLeggings, KKArmorMaterial.XEMNAS, EquipmentSlotType.LEGS),
			xemnas_Boots = createArmorItem(Strings.xemnasBoots, KKArmorMaterial.XEMNAS, EquipmentSlotType.FEET),

			heart = createNewItem(Strings.heart, new Item.Properties().group(KingdomKeys.miscGroup)),
			darkHeart = createNewItem(Strings.darkHeart, new Item.Properties().group(KingdomKeys.miscGroup)),
			pureHeart = createNewItem(Strings.pureHeart, new Item.Properties().group(KingdomKeys.miscGroup)),
			kingdomHearts = createNewItem(Strings.kingdom_hearts, new Item.Properties().group(KingdomKeys.miscGroup)),
			iceCream = createNewItem(Strings.iceCream, new Item.Properties().group(KingdomKeys.miscGroup).food(new Food.Builder().fastToEat().saturation(2.0f).hunger(2).build())),
			emptyBottle = createNewItem(Strings.emptyBottle, new Item.Properties().group(KingdomKeys.miscGroup)),

			disc_Birth_by_Sleep_A_Link_to_the_Future = createNewItem(Strings.Disc_Birth_by_Sleep_A_Link_to_the_Future, () -> new KKRecordItem(1, ModSounds.Record_Birth_by_Sleep_A_Link_to_the_Future, new Item.Properties().group(KingdomKeys.miscGroup), 7.29F)),
			disc_Darkness_of_the_Unknown = createNewItem(Strings.Disc_Darkness_of_the_Unknown, () -> new KKRecordItem(1, ModSounds.Record_Darkness_of_the_Unknown, new Item.Properties().group(KingdomKeys.miscGroup), 7.50F)),
			disc_Dearly_Beloved_Symphony_Version = createNewItem(Strings.Disc_Dearly_Beloved_Symphony_Version, () -> new KKRecordItem(1, ModSounds.Record_Dearly_Beloved_Symphony_Version, new Item.Properties().group(KingdomKeys.miscGroup), 2.33F)),
			disc_Dream_Drop_Distance_The_Next_Awakening = createNewItem(Strings.Disc_Dream_Drop_Distance_The_Next_Awakening, () -> new KKRecordItem(1, ModSounds.Record_Dream_Drop_Distance_The_Next_Awakening, new Item.Properties().group(KingdomKeys.miscGroup), 8.56F)),
			disc_Hikari_KINGDOM_Instrumental_Version = createNewItem(Strings.Disc_Hikari_KINGDOM_Instrumental_Version, () -> new KKRecordItem(1, ModSounds.Record_Hikari_KINGDOM_Instrumental_Version, new Item.Properties().group(KingdomKeys.miscGroup), 3.42F)),
			disc_L_Oscurita_Dell_Ignoto = createNewItem(Strings.Disc_L_Oscurita_Dell_Ignoto, () -> new KKRecordItem(1, ModSounds.Record_L_Oscurita_Dell_Ignoto, new Item.Properties().group(KingdomKeys.miscGroup), 4.33F)),
			disc_Musique_pour_la_tristesse_de_Xion = createNewItem(Strings.Disc_Musique_pour_la_tristesse_de_Xion, () -> new KKRecordItem(1, ModSounds.Record_Musique_pour_la_tristesse_de_Xion, new Item.Properties().group(KingdomKeys.miscGroup), 3.57F)),
			disc_No_More_Bugs_Bug_Version = createNewItem(Strings.Disc_No_More_Bugs_Bug_Version, () -> new KKRecordItem(1, ModSounds.Record_No_More_Bugs_Bug_Version, new Item.Properties().group(KingdomKeys.miscGroup), 3.17F)),
			disc_Organization_XIII = createNewItem(Strings.Disc_Organization_XIII, () -> new KKRecordItem(1, ModSounds.Record_Organization_XIII, new Item.Properties().group(KingdomKeys.miscGroup), 2.32F)),
			disc_Sanctuary = createNewItem(Strings.Disc_Sanctuary, () -> new KKRecordItem(1, ModSounds.Record_Sanctuary, new Item.Properties().group(KingdomKeys.miscGroup), 4.25F)),
			disc_Simple_And_Clean_PLANITb_Remix = createNewItem(Strings.Disc_Simple_And_Clean_PLANITb_Remix, () -> new KKRecordItem(1, ModSounds.Record_Simple_And_Clean_PLANITb_Remix, new Item.Properties().group(KingdomKeys.miscGroup), 2.37F)),
			disc_Sinister_Sundown = createNewItem(Strings.Disc_Sinister_Sundown, () -> new KKRecordItem(1, ModSounds.Record_Sinister_Sundown, new Item.Properties().group(KingdomKeys.miscGroup), 2.13F)),
			disc_The_13th_Anthology = createNewItem(Strings.Disc_The_13th_Anthology, () -> new KKRecordItem(1, ModSounds.Record_The_13th_Anthology, new Item.Properties().group(KingdomKeys.miscGroup), 6.38F)),

			blazing_crystal = createNewItem(Strings.SM_BlazingCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			blazing_gem = createNewItem(Strings.SM_BlazingGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			blazing_stone = createNewItem(Strings.SM_BlazingStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			blazing_shard = createNewItem(Strings.SM_BlazingShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			soothing_crystal = createNewItem(Strings.SM_SoothingCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup),  Strings.SM_Rank_S)),
			soothing_gem = createNewItem(Strings.SM_SoothingGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			soothing_stone = createNewItem(Strings.SM_SoothingStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			soothing_shard = createNewItem(Strings.SM_SoothingShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			writhing_crystal = createNewItem(Strings.SM_WrithingCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			writhing_gem = createNewItem(Strings.SM_WrithingGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			writhing_stone = createNewItem(Strings.SM_WrithingStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			writhing_shard = createNewItem(Strings.SM_WrithingShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			betwixt_crystal = createNewItem(Strings.SM_BetwixtCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			betwixt_gem = createNewItem(Strings.SM_BetwixtGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			betwixt_stone = createNewItem(Strings.SM_BetwixtShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			betwixt_shard = createNewItem(Strings.SM_BetwixtStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			wellspring_crystal = createNewItem(Strings.SM_WellspringCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			wellspring_gem = createNewItem(Strings.SM_WellspringGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			wellspring_stone = createNewItem(Strings.SM_WellspringStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			wellspring_shard = createNewItem(Strings.SM_WellspringShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			frost_crystal = createNewItem(Strings.SM_FrostCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			frost_gem = createNewItem(Strings.SM_FrostGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			frost_stone = createNewItem(Strings.SM_FrostStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			frost_shard = createNewItem(Strings.SM_FrostShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			lightning_crystal = createNewItem(Strings.SM_LightningCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			lightning_gem = createNewItem(Strings.SM_LightningGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			lightning_stone = createNewItem(Strings.SM_LightningStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			lightning_shard = createNewItem(Strings.SM_LightningShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			lucid_crystal = createNewItem(Strings.SM_LucidCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			lucid_gem = createNewItem(Strings.SM_LucidGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			lucid_stone = createNewItem(Strings.SM_LucidStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			lucid_shard = createNewItem(Strings.SM_LucidShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			hungry_crystal = createNewItem(Strings.SM_HungryCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			hungry_gem = createNewItem(Strings.SM_HungryGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			hungry_stone = createNewItem(Strings.SM_HungryStone,() -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup),  Strings.SM_Rank_B)),
			hungry_shard = createNewItem(Strings.SM_HungryShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			twilight_crystal = createNewItem(Strings.SM_TwilightCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			twilight_gem = createNewItem(Strings.SM_TwilightGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			twilight_stone = createNewItem(Strings.SM_TwilightShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			twilight_shard = createNewItem(Strings.SM_TwilightStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			mythril_crystal = createNewItem(Strings.SM_MythrilCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			mythril_gem = createNewItem(Strings.SM_MythrilGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			mythril_stone = createNewItem(Strings.SM_MythrilStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			mythril_shard = createNewItem(Strings.SM_MythrilShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			tranquility_crystal = createNewItem(Strings.SM_TranquilityCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			tranquility_gem = createNewItem(Strings.SM_TranquilityGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			tranquility_stone = createNewItem(Strings.SM_TranquilityStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			tranquility_shard = createNewItem(Strings.SM_TranquilityShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			sinister_crystal = createNewItem(Strings.SM_SinisterCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			sinister_gem = createNewItem(Strings.SM_SinisterGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			sinister_stone = createNewItem(Strings.SM_SinisterStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			sinister_shard = createNewItem(Strings.SM_SinisterShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			stormy_crystal = createNewItem(Strings.SM_StormyCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			stormy_gem = createNewItem(Strings.SM_StormyGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			stormy_stone = createNewItem(Strings.SM_StormyStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			stormy_shard = createNewItem(Strings.SM_StormyShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			remembrance_crystal = createNewItem(Strings.SM_RemembranceCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			remembrance_gem = createNewItem(Strings.SM_RemembranceGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			remembrance_stone = createNewItem(Strings.SM_RemembranceStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			remembrance_shard = createNewItem(Strings.SM_RemembranceShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			pulsing_crystal = createNewItem(Strings.SM_PulsingCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			pulsing_gem = createNewItem(Strings.SM_PulsingGem, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			pulsing_stone = createNewItem(Strings.SM_PulsingStone, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			pulsing_shard = createNewItem(Strings.SM_PulsingShard, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			orichalcumplus = createNewItem(Strings.SM_OrichalcumPlus, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			orichalcum = createNewItem(Strings.SM_Orichalcum, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			manifest_illusion = createNewItem(Strings.SM_ManifestIllusion, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			lost_illusion = createNewItem(Strings.SM_LostIllusion, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			fluorite = createNewItem(Strings.SM_Fluorite, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_C)),
			damascus = createNewItem(Strings.SM_Damascus, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_B)),
			adamantite = createNewItem(Strings.SM_Adamantite, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_A)),
			electrum = createNewItem(Strings.SM_Electrum, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			evanescent_crystal = createNewItem(Strings.SM_EvanescentCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),
			illusory_crystal = createNewItem(Strings.SM_IllusoryCrystal, () -> new SynthesisItem(new Item.Properties().group(KingdomKeys.miscGroup), Strings.SM_Rank_S)),

			fireSpell = createNewItem(Strings.SpellFire, () -> new MagicSpellItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID + ":" + Strings.Mag_Prefix + "fire")),
			blizzardSpell = createNewItem(Strings.SpellBlizzard, () -> new MagicSpellItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID + ":" + Strings.Mag_Prefix + "blizzard")),			
			waterSpell = createNewItem(Strings.SpellWater, () -> new MagicSpellItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID + ":" + Strings.Mag_Prefix + "water")),
			thunderSpell = createNewItem(Strings.SpellThunder, () -> new MagicSpellItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID + ":" + Strings.Mag_Prefix + "thunder")),
			cureSpell = createNewItem(Strings.SpellCure, () -> new MagicSpellItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID + ":" + Strings.Mag_Prefix + "cure")),
			aeroSpell = createNewItem(Strings.SpellAero, () -> new MagicSpellItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID + ":" + Strings.Mag_Prefix + "aero")),
			magnetSpell = createNewItem(Strings.SpellMagnet, () -> new MagicSpellItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID + ":" + Strings.Mag_Prefix + "magnet")),			
			reflectSpell= createNewItem(Strings.SpellReflect, () -> new MagicSpellItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID + ":" + Strings.Mag_Prefix + "reflect")),
			gravitySpell = createNewItem(Strings.SpellGravity, () -> new MagicSpellItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID + ":" + Strings.Mag_Prefix + "gravity")),
			stopSpell = createNewItem(Strings.SpellStop, () -> new MagicSpellItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID + ":" + Strings.Mag_Prefix + "stop")),
			
			valorOrb = createNewItem(Strings.LevelUpValor, () -> new UpgradeDriveFormItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID+":form_valor")),
			wisdomOrb = createNewItem(Strings.LevelUpWisdom, () -> new UpgradeDriveFormItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID+":form_wisdom")),			
			limitOrb = createNewItem(Strings.LevelUpLimit, () -> new UpgradeDriveFormItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID+":form_limit")),
			masterOrb = createNewItem(Strings.LevelUpMaster, () -> new UpgradeDriveFormItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID+":form_master")),
			finalOrb = createNewItem(Strings.LevelUpFinal, () -> new UpgradeDriveFormItem(new Item.Properties().group(KingdomKeys.miscGroup), KingdomKeys.MODID+":form_final")),
			
			synthesisBag = createNewItem("synthesis_bag", () -> new SynthesisBagItem(new Item.Properties().group(KingdomKeys.miscGroup).maxStackSize(1)));

	//Helper method to create item with the properties and registry name
	public static RegistryObject<Item> createNewItem(String name, Item.Properties properties) {
		return ITEMS.register(name, () -> new Item(properties));
	}

	public static <T extends Item> RegistryObject<T> createNewItem(String name, Supplier<? extends T> item) {
		return ITEMS.register(name, item);
	}

	public static RegistryObject<Item> createKeybladeItem(String name) {
		return ITEMS.register(name, () -> new KeybladeItem(new Item.Properties().group(KingdomKeys.keybladesGroup).maxStackSize(1)));
	}

	private static RegistryObject<Item> createArmorItem(String name, KKArmorMaterial material, EquipmentSlotType slot, String type) {
		return ITEMS.register(name, () -> new BaseArmorItem(material, slot, type));
	}

	private static RegistryObject<Item> createArmorItem(String name, KKArmorMaterial material, EquipmentSlotType slot) {
		return ITEMS.register(name, () -> new BaseArmorItem(material, slot, null));
	}
		/*
        malice = new EtherealBladeItem(Strings.malice),
        sanction = new EtherealBladeItem(Strings.sanction),
        overlord = new EtherealBladeItem(Strings.overlord),
        veneration = new EtherealBladeItem(Strings.veneration),
        autocracy = new EtherealBladeItem(Strings.autocracy),
        conquest = new EtherealBladeItem(Strings.conquest),
        terminus = new EtherealBladeItem(Strings.terminus),
        judgement = new EtherealBladeItem(Strings.judgement),
        discipline = new EtherealBladeItem(Strings.discipline),
        aristocracy = new EtherealBladeItem(Strings.aristocracy),
        superiority = new EtherealBladeItem(Strings.superiority),
        aggression = new EtherealBladeItem(Strings.aggression),
        fury = new EtherealBladeItem(Strings.fury),
        despair = new EtherealBladeItem(Strings.despair),
        triumph = new EtherealBladeItem(Strings.triumph),
        ruination = new EtherealBladeItem(Strings.ruination),
        domination = new EtherealBladeItem(Strings.domination),
        annihilation = new EtherealBladeItem(Strings.annihilation),
        tyrant = new EtherealBladeItem(Strings.tyrant),
        magnificence = new EtherealBladeItem(Strings.magnificence),
        infinity = new EtherealBladeItem(Strings.infinity),
        interdiction = new EtherealBladeItem(Strings.interdiction),
        roundFan = new EtherealBladeItem(Strings.roundFan),
        absolute = new EtherealBladeItem(Strings.absolute),
        standalone = new ArrowgunsItem(Strings.standalone),
        killerbee = new ArrowgunsItem(Strings.killerbee),
        stingray = new ArrowgunsItem(Strings.stingray),
        counterweight = new ArrowgunsItem(Strings.counterweight),
        precision = new ArrowgunsItem(Strings.precision),
        dualHead = new ArrowgunsItem(Strings.dualHead),
        bahamut = new ArrowgunsItem(Strings.bahamut),
        gullwing = new ArrowgunsItem(Strings.gullwing),
        blueFrame = new ArrowgunsItem(Strings.blueFrame),
        starShell = new ArrowgunsItem(Strings.starShell),
        sunrise = new ArrowgunsItem(Strings.sunrise),
        ignition = new ArrowgunsItem(Strings.ignition),
        armstrong = new ArrowgunsItem(Strings.armstrong),
        hardBoiledHeat = new ArrowgunsItem(Strings.hardBoiledHeat),
        diabloEye = new ArrowgunsItem(Strings.diabloEye),
        doubleTap = new ArrowgunsItem(Strings.doubleTap),
        stardust = new ArrowgunsItem(Strings.stardust),
        energyMuzzle = new ArrowgunsItem(Strings.energyMuzzle),
        crimeAndPunishment = new ArrowgunsItem(Strings.crimeAndPunishment),
        cupidsArrow = new ArrowgunsItem(Strings.cupidsArrow),
        finalWeapon = new ArrowgunsItem(Strings.finalWeapon),
        sharpshooter = new ArrowgunsItem(Strings.sharpshooter),
        dryer = new ArrowgunsItem(Strings.dryer),
        trumpet = new ArrowgunsItem(Strings.trumpet),
        zephyr = new LanceItem(Strings.zephyr),
        moonglade = new LanceItem(Strings.moonglade),
        aer = new LanceItem(Strings.aer),
        nescience = new LanceItem(Strings.nescience),
        brume = new LanceItem(Strings.brume),
        asura = new LanceItem(Strings.asura),
        crux = new LanceItem(Strings.crux),
        paladin = new LanceItem(Strings.paladin),
        fellking = new LanceItem(Strings.fellking),
        nightcloud = new LanceItem(Strings.nightcloud),
        shimmer = new LanceItem(Strings.shimmer),
        vortex = new LanceItem(Strings.vortex),
        scission = new LanceItem(Strings.scission),
        heavenfall = new LanceItem(Strings.heavenfall),
        aether = new LanceItem(Strings.aether),
        mazzaroth = new LanceItem(Strings.mazzaroth),
        hegemon = new LanceItem(Strings.hegemon),
        foxfire = new LanceItem(Strings.foxfire),
        yaksha = new LanceItem(Strings.yaksha),
        cynosura = new LanceItem(Strings.cynosura),
        dragonreign = new LanceItem(Strings.dragonreign),
        lindworm = new LanceItem(Strings.lindworm),
        broom = new LanceItem(Strings.broom),
        wyvern = new LanceItem(Strings.wyvern),
        testerZero = new OrgShieldItem(Strings.testerZero),
        productOne = new OrgShieldItem(Strings.productOne),
        deepFreeze = new OrgShieldItem(Strings.deepFreeze),
        cryoliteShield = new OrgShieldItem(Strings.cryoliteShield),
        falseTheory = new OrgShieldItem(Strings.falseTheory),
        glacier = new OrgShieldItem(Strings.glacier),
        absoluteZero = new OrgShieldItem(Strings.absoluteZero),
        gunz = new OrgShieldItem(Strings.gunz),
        mindel = new OrgShieldItem(Strings.mindel),
        snowslide = new OrgShieldItem(Strings.snowslide),
        iceberg = new OrgShieldItem(Strings.iceberg),
        inquisition = new OrgShieldItem(Strings.inquisition),
        scrutiny = new OrgShieldItem(Strings.scrutiny),
        empiricism = new OrgShieldItem(Strings.empiricism),
        edification = new OrgShieldItem(Strings.edification),
        contrivance = new OrgShieldItem(Strings.contrivance),
        wurm = new OrgShieldItem(Strings.wurm),
        subzero = new OrgShieldItem(Strings.subzero),
        coldBlood = new OrgShieldItem(Strings.coldBlood),
        diamondShield = new OrgShieldItem(Strings.diamondShield),
        aegis = new OrgShieldItem(Strings.aegis),
        frozenPride = new OrgShieldItem(Strings.frozenPride),
        potLid = new OrgShieldItem(Strings.potLid),
        snowman = new OrgShieldItem(Strings.snowman),
        reticence = new AxeSwordItem(Strings.reticence),
        goliath = new AxeSwordItem(Strings.goliath),
        copperRed = new AxeSwordItem(Strings.copperRed),
        daybreak = new AxeSwordItem(Strings.daybreak),
        colossus = new AxeSwordItem(Strings.colossus),
        ursaMajor = new AxeSwordItem(Strings.ursaMajor),
        megacosm = new AxeSwordItem(Strings.megacosm),
        terrene = new AxeSwordItem(Strings.terrene),
        fuligin = new AxeSwordItem(Strings.fuligin),
        hardWinter = new AxeSwordItem(Strings.hardWinter),
        firefly = new AxeSwordItem(Strings.firefly),
        harbinger = new AxeSwordItem(Strings.harbinger),
        redwood = new AxeSwordItem(Strings.redwood),
        sequoia = new AxeSwordItem(Strings.sequoia),
        ironBlack = new AxeSwordItem(Strings.ironBlack),
        earthshine = new AxeSwordItem(Strings.earthshine),
        octiron = new AxeSwordItem(Strings.octiron),
        hyperion = new AxeSwordItem(Strings.hyperion),
        clarity = new AxeSwordItem(Strings.clarity),
        oneThousandAndOneNights = new AxeSwordItem(Strings.oneThousandAndOneNights),
        cardinalVirtue = new AxeSwordItem(Strings.cardinalVirtue),
        skysplitter = new AxeSwordItem(Strings.skysplitter),
        bleepBloopBop = new AxeSwordItem(Strings.bleepBloopBop),
        monolith = new AxeSwordItem(Strings.monolith),
        blackPrimer = new LexiconItem(Strings.blackPrimer),
        whiteTome = new LexiconItem(Strings.whiteTome),
        illicitResearch = new LexiconItem(Strings.illicitResearch),
        buriedSecrets = new LexiconItem(Strings.buriedSecrets),
        arcaneCompendium = new LexiconItem(Strings.arcaneCompendium),
        dissentersNotes = new LexiconItem(Strings.dissentersNotes),
        nefariousCodex = new LexiconItem(Strings.nefariousCodex),
        mysticAlbum = new LexiconItem(Strings.mysticAlbum),
        cursedManual = new LexiconItem(Strings.cursedManual),
        tabooText = new LexiconItem(Strings.tabooText),
        eldritchEsoterica = new LexiconItem(Strings.eldritchEsoterica),
        freakishBestiary = new LexiconItem(Strings.freakishBestiary),
        madmansVita = new LexiconItem(Strings.madmansVita),
        untitledWritings = new LexiconItem(Strings.untitledWritings),
        abandonedDogma = new LexiconItem(Strings.abandonedDogma),
        atlasOfOmens = new LexiconItem(Strings.atlasOfOmens),
        revoltingScrapbook = new LexiconItem(Strings.revoltingScrapbook),
        lostHeterodoxy = new LexiconItem(Strings.lostHeterodoxy),
        otherworldlyTales = new LexiconItem(Strings.otherworldlyTales),
        indescribableLore = new LexiconItem(Strings.indescribableLore),
        radicalTreatise = new LexiconItem(Strings.radicalTreatise),
        bookOfRetribution = new LexiconItem(Strings.bookOfRetribution),
        midnightSnack = new LexiconItem(Strings.midnightSnack),
        dearDiary = new LexiconItem(Strings.dearDiary),
        newMoon = new ClaymoreItem(Strings.newMoon),
        werewolf = new ClaymoreItem(Strings.werewolf),
        artemis = new ClaymoreItem(Strings.artemis),
        luminary = new ClaymoreItem(Strings.luminary),
        selene = new ClaymoreItem(Strings.selene),
        moonrise = new ClaymoreItem(Strings.moonrise),
        astrologia = new ClaymoreItem(Strings.astrologia),
        crater = new ClaymoreItem(Strings.crater),
        lunarPhase = new ClaymoreItem(Strings.lunarPhase),
        crescent = new ClaymoreItem(Strings.crescent),
        gibbous = new ClaymoreItem(Strings.gibbous),
        berserker = new ClaymoreItem(Strings.berserker),
        twilight = new ClaymoreItem(Strings.twilight),
        queenOfTheNight = new ClaymoreItem(Strings.queenOfTheNight),
        balsamicMoon = new ClaymoreItem(Strings.balsamicMoon),
        orbit = new ClaymoreItem(Strings.orbit),
        lightYear = new ClaymoreItem(Strings.lightYear),
        kingOfTheNight = new ClaymoreItem(Strings.kingOfTheNight),
        moonset = new ClaymoreItem(Strings.moonset),
        horoscope = new ClaymoreItem(Strings.horoscope),
        dichotomy = new ClaymoreItem(Strings.dichotomy),
        lunatic = new ClaymoreItem(Strings.lunatic),
        justDesserts = new ClaymoreItem(Strings.justDesserts),
        bunnymoon = new ClaymoreItem(Strings.bunnymoon),
        ashes = new ChakramItem(Strings.ashes),
        doldrums = new ChakramItem(Strings.doldrums),
        delayedAction = new ChakramItem(Strings.delayedAction),
        diveBombers = new ChakramItem(Strings.diveBombers),
        combustion = new ChakramItem(Strings.combustion),
        moulinRouge = new ChakramItem(Strings.moulinRouge),
        blazeOfGlory = new ChakramItem(Strings.blazeOfGlory),
        prometheus = new ChakramItem(Strings.prometheus),
        ifrit = new ChakramItem(Strings.ifrit),
        magmaOcean = new ChakramItem(Strings.magmaOcean),
        volcanics = new ChakramItem(Strings.volcanics),
        inferno = new ChakramItem(Strings.inferno),
        sizzlingEdge = new ChakramItem(Strings.sizzlingEdge),
        corona = new ChakramItem(Strings.corona),
        ferrisWheel = new ChakramItem(Strings.ferrisWheel),
        burnout = new ChakramItem(Strings.burnout),
        omegaTrinity = new ChakramItem(Strings.omegaTrinity),
        outbreak = new ChakramItem(Strings.outbreak),
        doubleEdge = new ChakramItem(Strings.doubleEdge),
        wildfire = new ChakramItem(Strings.wildfire),
        prominence = new ChakramItem(Strings.prominence),
        eternalFlames = new ChakramItem(Strings.eternalFlames),
        pizzaCut = new ChakramItem(Strings.pizzaCut),
        conformers = new ChakramItem(Strings.conformers),
        basicModel = new SitarItem(Strings.basicModel),
        tuneUp = new SitarItem(Strings.tuneUp),
        quartet = new SitarItem(Strings.quartet),
        quintet = new SitarItem(Strings.quintet),
        overture = new SitarItem(Strings.overture),
        oldHand = new SitarItem(Strings.oldHand),
        daCapo = new SitarItem(Strings.daCapo),
        powerChord = new SitarItem(Strings.powerChord),
        fermata = new SitarItem(Strings.fermata),
        interlude = new SitarItem(Strings.interlude),
        serenade = new SitarItem(Strings.serenade),
        songbird = new SitarItem(Strings.songbird),
        riseToFame = new SitarItem(Strings.riseToFame),
        rockStar = new SitarItem(Strings.rockStar),
        eightFinger = new SitarItem(Strings.eightFinger),
        concerto = new SitarItem(Strings.concerto),
        harmonics = new SitarItem(Strings.harmonics),
        millionBucks = new SitarItem(Strings.millionBucks),
        fortissimo = new SitarItem(Strings.fortissimo),
        upToEleven = new SitarItem(Strings.upToEleven),
        sanctuary = new SitarItem(Strings.sanctuary),
        arpeggio = new SitarItem(Strings.arpeggio),
        princeOfAwesome = new SitarItem(Strings.princeOfAwesome),
        afterSchool = new SitarItem(Strings.afterSchool),
        theFool = new CardItem(Strings.theFool),
        theMagician = new CardItem(Strings.theMagician),
        theStar = new CardItem(Strings.theStar),
        theMoon = new CardItem(Strings.theMoon),
        justice = new CardItem(Strings.justice),
        theHierophant = new CardItem(Strings.theHierophant),
        theWorld = new CardItem(Strings.theWorld),
        temperance = new CardItem(Strings.temperance),
        theHighPriestess = new CardItem(Strings.theHighPriestess),
        theTower = new CardItem(Strings.theTower),
        theHangedMan = new CardItem(Strings.theHangedMan),
        death = new CardItem(Strings.death),
        theHermit = new CardItem(Strings.theHermit),
        strength = new CardItem(Strings.strength),
        theLovers = new CardItem(Strings.theLovers),
        theChariot = new CardItem(Strings.theChariot),
        theSun = new CardItem(Strings.theSun),
        theDevil = new CardItem(Strings.theDevil),
        theEmpress = new CardItem(Strings.theEmpress),
        theEmperor = new CardItem(Strings.theEmperor),
        theJoker = new CardItem(Strings.theJoker),
        fairGame = new CardItem(Strings.fairGame),
        finestFantasy13 = new CardItem(Strings.finestFantasy13),
        highRollersSecret = new CardItem(Strings.highRollersSecret),
        fickleErica = new ScytheItem(Strings.fickleErica),
        jiltedAnemone = new ScytheItem(Strings.jiltedAnemone),
        proudAmaryllis = new ScytheItem(Strings.proudAmaryllis),
        madSafflower = new ScytheItem(Strings.madSafflower),
        poorMelissa = new ScytheItem(Strings.poorMelissa),
        tragicAllium = new ScytheItem(Strings.tragicAllium),
        mournfulCineria = new ScytheItem(Strings.mournfulCineria),
        pseudoSilene = new ScytheItem(Strings.pseudoSilene),
        faithlessDigitalis = new ScytheItem(Strings.faithlessDigitalis),
        grimMuscari = new ScytheItem(Strings.grimMuscari),
        docileVallota = new ScytheItem(Strings.docileVallota),
        quietBelladonna = new ScytheItem(Strings.quietBelladonna),
        partingIpheion = new ScytheItem(Strings.partingIpheion),
        loftyGerbera = new ScytheItem(Strings.loftyGerbera),
        gallantAchillea = new ScytheItem(Strings.gallantAchillea),
        noblePeony = new ScytheItem(Strings.noblePeony),
        fearsomeAnise = new ScytheItem(Strings.fearsomeAnise),
        vindictiveThistle = new ScytheItem(Strings.vindictiveThistle),
        fairHelianthus = new ScytheItem(Strings.fairHelianthus),
        solemnMagnolia = new ScytheItem(Strings.solemnMagnolia),
        hallowedLotus = new ScytheItem(Strings.hallowedLotus),
        gracefulDahlia = new ScytheItem(Strings.gracefulDahlia),
        stirringLadle = new ScytheItem(Strings.stirringLadle),
        daintyBellflowers = new ScytheItem(Strings.daintyBellflowers),
        trancheuse = new KnifeItem(Strings.trancheuse),
        orage = new KnifeItem(Strings.orage),
        tourbillon = new KnifeItem(Strings.tourbillon),
        tempete = new KnifeItem(Strings.tempete),
        carmin = new KnifeItem(Strings.carmin),
        meteore = new KnifeItem(Strings.meteore),
        etoile = new KnifeItem(Strings.etoile),
        irregulier = new KnifeItem(Strings.irregulier),
        dissonance = new KnifeItem(Strings.dissonance),
        eruption = new KnifeItem(Strings.eruption),
        soleilCouchant = new KnifeItem(Strings.soleilCouchant),
        indigo = new KnifeItem(Strings.indigo),
        vague = new KnifeItem(Strings.vague),
        deluge = new KnifeItem(Strings.deluge),
        rafale = new KnifeItem(Strings.rafale),
        typhon = new KnifeItem(Strings.typhon),
        extirpeur = new KnifeItem(Strings.extirpeur),
        croixDuSud = new KnifeItem(Strings.croixDuSud),
        lumineuse = new KnifeItem(Strings.lumineuse),
        clairDeLune = new KnifeItem(Strings.clairDeLune),
        volDeNuit = new KnifeItem(Strings.volDeNuit),
        foudre = new KnifeItem(Strings.foudre),
        demoiselle = new KnifeItem(Strings.demoiselle),
        ampoule = new KnifeItem(Strings.ampoule)
        */

					/*
        @SubscribeEvent
    	public static void registerContainers(RegistryEvent.Register<ContainerType<?>> evt) {
    		IForgeRegistry<ContainerType<?>> r = evt.getRegistry();

    		ContainerType<SynthesisBagContainer> bag = IForgeContainerType.create(SynthesisBagContainer::fromNetwork);
    		register(r, bag, synthesisBag.get().getRegistryName());

    		DistExecutor.runWhenOn(Dist.CLIENT, () -> () -> {
    			ScreenManager.registerFactory(bag, SynthesisBagGui::new);
    		});
    	}
        

    	public static <V extends IForgeRegistryEntry<V>> void register(IForgeRegistry<V> reg, IForgeRegistryEntry<V> thing, ResourceLocation name) {
    		reg.register(thing.setRegistryName(name));
    	}

    	public static <V extends IForgeRegistryEntry<V>> void register(IForgeRegistry<V> reg, IForgeRegistryEntry<V> thing, String name) {
    		register(reg, thing, new ResourceLocation(KingdomKeys.MODID, name));
    	}
    	*/
}
