package online.kingdomkeys.kingdomkeys.world.features;

import com.mojang.serialization.Codec;
import net.minecraft.core.BlockPos;
import net.minecraft.util.Mth;
import net.minecraft.util.RandomSource;
import net.minecraft.world.level.WorldGenLevel;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.levelgen.Heightmap;
import net.minecraft.world.level.levelgen.feature.Feature;
import net.minecraft.world.level.levelgen.feature.FeaturePlaceContext;
import net.minecraft.world.level.levelgen.feature.configurations.NoneFeatureConfiguration;
import net.minecraft.world.phys.Vec3;
import online.kingdomkeys.kingdomkeys.block.ModBlocks;

/**
 * Stone arches generated by code so they are not identical
 */
public class DarkArchFeature extends Feature<NoneFeatureConfiguration> {
	private static final int MAX_SPAN = 22;
	private static final float GLOW_CHANCE = 0.05F;
	// Below this the part is too thin to be worth drawing as a sphere
	private static final float MIN_RADIUS = 0.6F;

	public DarkArchFeature(Codec<NoneFeatureConfiguration> codec) {
		super(codec);
	}

	@Override
	public boolean place(FeaturePlaceContext<NoneFeatureConfiguration> context) {
		WorldGenLevel level = context.level();
		RandomSource random = context.random();
		BlockPos origin = context.origin();

		// Roots on the sea floor rather than the water surface so they don't just float there
		int floorY = level.getHeight(Heightmap.Types.OCEAN_FLOOR_WG, origin.getX(), origin.getZ());
		BlockPos base = new BlockPos(origin.getX(), floorY, origin.getZ());

		// A lone pillar now and then breaks up a coastline of nothing but arches
		if (random.nextFloat() < 0.25F) {
			growPillar(level, random, base);
			return true;
		}

		int arches = 1 + random.nextInt(2);
		for (int i = 0; i < arches; i++) {
			BlockPos footing = base.offset(random.nextInt(9) - 4, 0, random.nextInt(9) - 4);
			growArch(level, random, footing);
		}
		return true;
	}

	private void growPillar(WorldGenLevel level, RandomSource random, BlockPos base) {
		int height = 9 + random.nextInt(10);
		float lean = 0.15F + random.nextFloat() * 0.25F;
		double leanAngle = random.nextDouble() * Math.PI * 2;

		Vec3 from = new Vec3(base.getX() + 0.5, base.getY() - 2, base.getZ() + 0.5);
		Vec3 to = from.add(Math.cos(leanAngle) * height * lean, height, Math.sin(leanAngle) * height * lean);

		float radius = 1.8F + random.nextFloat() * 1.2F;
		drawLimb(level, random, from, to, radius, radius * 0.15F);

		if (random.nextBoolean()) {
			branchFrom(level, random, to, radius * 0.5F, 2);
		}
	}

	private void growArch(WorldGenLevel level, RandomSource random, BlockPos base) {
		double heading = random.nextDouble() * Math.PI * 2;
		int span = 11 + random.nextInt(MAX_SPAN - 11);
		int rise = 7 + random.nextInt(9);

		double dx = Math.cos(heading) * span;
		double dz = Math.sin(heading) * span;

		// Slightly lower to make more likely both feet hit the floor
		Vec3 footA = new Vec3(base.getX() + 0.5, base.getY() - 2, base.getZ() + 0.5);
		Vec3 footB = footA.add(dx, 0, dz);

		float baseRadius = 1.7F + random.nextFloat() * 1.1F;
		int steps = span + rise;

		Vec3 previous = null;
		for (int i = 0; i <= steps; i++) {
			float t = (float) i / steps;
			// Parabola
			double y = footA.y + Mth.sin((float) (t * Math.PI)) * rise;
			double wobble = Mth.sin(t * 6F) * 1.4;

			Vec3 point = new Vec3(Mth.lerp(t, footA.x, footB.x) - Math.sin(heading) * wobble, y, Mth.lerp(t, footA.z, footB.z) + Math.cos(heading) * wobble);

			// Thick at both feet thin at the crown
			float radius = baseRadius * (0.35F + 0.65F * Math.abs(0.5F - t) * 2F);

			if (previous != null) {
				drawLimb(level, random, previous, point, radius, radius);
			}
			previous = point;

			// Branches spring from the legs, not the crown
			if (i > 2 && i < steps - 2 && random.nextFloat() < 0.09F) {
				branchFrom(level, random, point, radius * 0.6F, 2);
			}
		}
	}

	// Recursive function to generate branches, shorter every time
	private void branchFrom(WorldGenLevel level, RandomSource random, Vec3 from, float radius, int depth) {
		if (depth <= 0 || radius < MIN_RADIUS) {
			return;
		}

		int branches = 1 + random.nextInt(2);
		for (int i = 0; i < branches; i++) {
			double angle = random.nextDouble() * Math.PI * 2;
			double length = 3 + random.nextDouble() * 5;
			double climb = 0.2 + random.nextDouble() * 0.8;

			Vec3 to = from.add(Math.cos(angle) * length, climb * length, Math.sin(angle) * length);
			drawLimb(level, random, from, to, radius, radius * 0.4F);

			branchFrom(level, random, to, radius * 0.55F, depth - 1);
		}
	}

	// Walks a line placing spheres, shrinking radius progressively
	private void drawLimb(WorldGenLevel level, RandomSource random, Vec3 from, Vec3 to, float fromRadius, float toRadius) {
		double distance = from.distanceTo(to);
		int steps = Math.max(1, (int) (distance * 2));

		for (int i = 0; i <= steps; i++) {
			float t = (float) i / steps;
			Vec3 point = from.lerp(to, t);
			float radius = Mth.lerp(t, fromRadius, toRadius);
			placeSphere(level, random, point, radius);
		}
	}

	private void placeSphere(WorldGenLevel level, RandomSource random, Vec3 centre, float radius) {
		if (radius < MIN_RADIUS) {
			radius = MIN_RADIUS;
		}

		int r = Mth.ceil(radius);
		BlockPos.MutableBlockPos pos = new BlockPos.MutableBlockPos();

		for (int x = -r; x <= r; x++) {
			for (int y = -r; y <= r; y++) {
				for (int z = -r; z <= r; z++) {
					// Jitter to avoid them looking perfect
					if (x * x + y * y + z * z > radius * radius + random.nextFloat() * 0.6F) {
						continue;
					}

					pos.set(centre.x + x, centre.y + y, centre.z + z);
					if (!level.isOutsideBuildHeight(pos) && canReplace(level, pos)) {
						level.setBlock(pos, material(random), 2);
					}
				}
			}
		}
	}

	private boolean canReplace(WorldGenLevel level, BlockPos pos) {
		BlockState state = level.getBlockState(pos);
		return state.isAir() || state.getFluidState().isSource() || state.canBeReplaced();
	}

	private BlockState material(RandomSource random) {
		return random.nextFloat() < GLOW_CHANCE ? ModBlocks.rodCrackedStone.get().defaultBlockState() : ModBlocks.rodStone.get().defaultBlockState();
	}
}
